/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/assets/ProductShowcase/scene-3.glb -o features/ProductShowcase/components/Models/Sorktop.tsx -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		FluffyThing: THREE.Mesh;
		GardenLight001: THREE.Mesh;
		GardenThing: THREE.Mesh;
		Plant001: THREE.Mesh;
	};
	materials: {
		["Material.Scene2"]: THREE.MeshStandardMaterial;
	};
};

export function GardenLighModel(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/assets/ProductShowcase/scene-3.glb"
	) as GLTFResult;
	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.GardenLight001.geometry}
				material={materials["Material.Scene2"]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/assets/ProductShowcase/scene-3.glb");
