/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/assets/ProductShowcase/scene-1.glb -o features/ProductShowcase/components/Models/worktop.tsx -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		ChairPyramid: THREE.Mesh;
		Pillow001: THREE.Mesh;
		Sofa001: THREE.Mesh;
		Lamp001: THREE.Mesh;
	};
	materials: {
		["Material.Scene1"]: THREE.MeshStandardMaterial;
	};
};

export function WorktopModel(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/assets/ProductShowcase/scene-1.glb"
	) as GLTFResult;
	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.ChairPyramid.geometry}
				material={materials["Material.Scene1"]}
				rotation={[0, 1.045, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/assets/ProductShowcase/scene-1.glb");
