/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/assets/RagingSea/boat.glb -o features/RagingSea/components/BoatModel.tsx -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";
import BoatLamps from "./BoatLamps";
import BoatLampLights from "./BoatLampLights";

type GLTFResult = GLTF & {
	nodes: {
		Crane: THREE.Mesh;
		Cube_8_4: THREE.Mesh;
		Cube_8_5: THREE.Mesh;
		Cube_8_6: THREE.Mesh;
		Mesh166: THREE.Mesh;
		Mesh166_1: THREE.Mesh;
		Mesh165: THREE.Mesh;
		Mesh165_1: THREE.Mesh;
		Mesh164: THREE.Mesh;
		Mesh164_1: THREE.Mesh;
		Mesh163: THREE.Mesh;
		Mesh163_1: THREE.Mesh;
		Mesh162: THREE.Mesh;
		Mesh162_1: THREE.Mesh;
		Mesh161: THREE.Mesh;
		Mesh161_1: THREE.Mesh;
		Mesh160: THREE.Mesh;
		Mesh160_1: THREE.Mesh;
		Mesh159: THREE.Mesh;
		Mesh159_1: THREE.Mesh;
		Cylinder: THREE.Mesh;
		Cylinder_1_7: THREE.Mesh;
		Cylinder_27: THREE.Mesh;
		Cylinder_2_7: THREE.Mesh;
		Cylinder_3_8: THREE.Mesh;
		Cylinder_4_8: THREE.Mesh;
		Cylinder_1_5: THREE.Mesh;
		Cylinder_25: THREE.Mesh;
		Cylinder_2_6: THREE.Mesh;
		Cylinder_3_7: THREE.Mesh;
		Cylinder_4_7: THREE.Mesh;
		Cylinder_1_3: THREE.Mesh;
		Cylinder_23: THREE.Mesh;
		Cylinder_2_4: THREE.Mesh;
		Cylinder_3_5: THREE.Mesh;
		Cylinder_4_5: THREE.Mesh;
		Cylinder_1_2: THREE.Mesh;
		Cylinder_22: THREE.Mesh;
		Cylinder_2_3: THREE.Mesh;
		Cylinder_3_4: THREE.Mesh;
		Cylinder_4_4: THREE.Mesh;
		Cylinder_1_4: THREE.Mesh;
		Cylinder_24: THREE.Mesh;
		Cylinder_2_5: THREE.Mesh;
		Cylinder_3_6: THREE.Mesh;
		Cylinder_4_6: THREE.Mesh;
		Cylinder_1_6: THREE.Mesh;
		Cylinder_26: THREE.Mesh;
		Cylinder_6_4: THREE.Mesh;
		Cube_13_2: THREE.Mesh;
		Cube_1_3: THREE.Mesh;
		Cylinder_5_23: THREE.Mesh;
		Cylinder_5_17: THREE.Mesh;
		Cylinder_5_16: THREE.Mesh;
		Cylinder_5_18: THREE.Mesh;
		Cylinder_5_15: THREE.Mesh;
		Cylinder_5_20: THREE.Mesh;
		Cylinder_5_19: THREE.Mesh;
		Cylinder_5_22: THREE.Mesh;
		Cylinder_5_13: THREE.Mesh;
		Cylinder_5_14: THREE.Mesh;
		Cylinder_5_21: THREE.Mesh;
		Cylinder_5_9: THREE.Mesh;
		Cylinder_5_8: THREE.Mesh;
		Cylinder_5_6: THREE.Mesh;
		Cylinder_4_3: THREE.Mesh;
		Cylinder_5_11: THREE.Mesh;
		Cylinder_5_10: THREE.Mesh;
		Cylinder_5_12: THREE.Mesh;
		Cylinder_2_2: THREE.Mesh;
		Cylinder_3_3: THREE.Mesh;
		Mesh149: THREE.Mesh;
		Mesh149_1: THREE.Mesh;
		Mesh149_2: THREE.Mesh;
		Mesh149_3: THREE.Mesh;
		Mesh149_4: THREE.Mesh;
		Mesh149_5: THREE.Mesh;
		Mesh149_6: THREE.Mesh;
		Mesh149_7: THREE.Mesh;
	};
	materials: {
		["Black Parts"]: THREE.MeshStandardMaterial;
		["Body 1"]: THREE.MeshStandardMaterial;
		Boat: THREE.MeshStandardMaterial;
		Redparts: THREE.MeshStandardMaterial;
		Floor: THREE.MeshStandardMaterial;
		["Glass.001"]: THREE.MeshStandardMaterial;
		Light: THREE.MeshStandardMaterial;
		["Redparts.001"]: THREE.MeshStandardMaterial;
	};
};

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

type Props = JSX.IntrinsicElements["group"] & {
	uBigWavesElevation: number;
	uBigWavesFrequency: [number, number];
	uBigWavesSpeed: number;
};

export function BoatModel({
	uBigWavesElevation,
	uBigWavesFrequency,
	uBigWavesSpeed,
	...props
}: Props) {
	const { nodes, materials } = useGLTF(
		"/assets/RagingSea/boat.glb"
	) as GLTFResult;

	const ref = useRef<THREE.Group>(null);
	const prevElevation = useRef(0);

	useFrame(({ clock }, delta) => {
		if (ref.current) {
			const elapsedTime = clock.getElapsedTime();

			const elevation =
				Math.sin(0 + elapsedTime * uBigWavesSpeed) *
				Math.sin(0 + elapsedTime * uBigWavesSpeed) *
				uBigWavesElevation;

			ref.current.position.y = elevation - 0.075;

			easing.damp(
				ref.current.rotation,
				"z",
				(prevElevation.current > elevation ? -1 : 1) *
					Math.min(elevation * 2, 0.25),
				0.3,
				delta
			);

			prevElevation.current = elevation;
		}
	});

	return (
		<group
			{...props}
			ref={ref}
			dispose={null}
		>
			<group
				position={[0.69, 0.148, -0.688]}
				rotation={[1.535, -0.017, 3.141]}
				scale={0.01}
			>
				<group
					position={[-30.972, -297.878, -320.484]}
					rotation={[-0.027, 0, Math.PI]}
				>
					<mesh
						geometry={nodes.Crane.geometry}
						material={materials["Black Parts"]}
						position={[1.172, 8.665, -19.247]}
						rotation={[-0.027, 0, -Math.PI]}
						castShadow
					/>
				</group>
				<group position={[-14.555, 74.036, -486.43]}>
					<group
						position={[144.257, 102.464, 0]}
						rotation={[-Math.PI, 0, -Math.PI]}
					>
						<mesh
							geometry={nodes.Cube_8_4.geometry}
							material={materials["Body 1"]}
							position={[-26.646, 143.605, 1.814]}
						/>
					</group>
					<group
						position={[-14.68, -201.064, 0]}
						rotation={[0, 0, Math.PI / 2]}
					>
						<mesh
							geometry={nodes.Cube_8_5.geometry}
							material={materials["Body 1"]}
							position={[-26.646, 143.604, 1.814]}
						/>
					</group>
					<group position={[-129.577, 98.6, 0]}>
						<mesh
							geometry={nodes.Cube_8_6.geometry}
							material={materials["Body 1"]}
							position={[-26.646, 147.084, 1.813]}
						/>
					</group>
				</group>
				<group position={[-7.953, 128.286, -513.97]}>
					<BoatLamps
						position={[110.104, -22.972, -83.272]}
						rotation={[0, -0.084, 0]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLamps
						position={[-110.825, -22.972, -83.272]}
						rotation={[0, 0.084, Math.PI]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLamps
						position={[-91.61, 122.12, -83.272]}
						rotation={[0.084, 0, Math.PI / 2]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLamps
						position={[91.416, 122.12, -83.272]}
						rotation={[0.084, 0, Math.PI / 2]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLamps
						position={[100.66, 187.459, 82.31]}
						rotation={[0.084, 0, Math.PI / 2]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLamps
						position={[-100.203, 187.459, 82.31]}
						rotation={[0.084, 0, Math.PI / 2]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLamps
						position={[100.66, -286.607, 84.234]}
						rotation={[-0.084, 0, -Math.PI / 2]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLamps
						position={[-100.203, -286.607, 84.234]}
						rotation={[-0.084, 0, -Math.PI / 2]}
						nodes={nodes}
						materials={materials}
					/>

					<BoatLampLights />
				</group>
				<group
					position={[-233.45, -184.172, -275.963]}
					rotation={[-0.027, 0, -Math.PI / 2]}
				>
					<mesh
						geometry={nodes.Cylinder.geometry}
						material={nodes.Cylinder.material}
						position={[-38.177, 2.343, -87.31]}
						rotation={[0, -1.571, 0]}
					/>
				</group>
				<group position={[32.069, 109.414, -277.962]}>
					<group
						position={[-7.365, 473.421, 1.998]}
						rotation={[-0.027, 0, 0]}
					>
						<mesh
							geometry={nodes.Cylinder_1_7.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, -0.323, 12.076]}
						/>
						<mesh
							geometry={nodes.Cylinder_27.geometry}
							material={materials["Black Parts"]}
							position={[-28.561, 2.267, -79.44]}
							rotation={[0, -1.571, 0]}
						/>
						<mesh
							geometry={nodes.Cylinder_2_7.geometry}
							material={materials["Black Parts"]}
							position={[-55.968, 1.175, -43.906]}
						/>
						<mesh
							geometry={nodes.Cylinder_3_8.geometry}
							material={materials["Black Parts"]}
							position={[-3.356, 1.175, -43.906]}
						/>
						<mesh
							geometry={nodes.Cylinder_4_8.geometry}
							material={materials["Black Parts"]}
							position={[0, -0.323, 12.076]}
						/>
					</group>
					<group
						position={[182.03, 69.531, 1.998]}
						rotation={[-0.027, 0, -Math.PI / 2]}
					>
						<mesh
							geometry={nodes.Cylinder_1_5.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, -0.323, 12.076]}
						/>
						<mesh
							geometry={nodes.Cylinder_25.geometry}
							material={materials["Black Parts"]}
							position={[-38.177, 2.343, -87.31]}
							rotation={[0, -1.571, 0]}
						/>
						<mesh
							geometry={nodes.Cylinder_2_6.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, 1.175, -43.906]}
						/>
						<mesh
							geometry={nodes.Cylinder_3_7.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, 1.175, -43.347]}
						/>
						<mesh
							geometry={nodes.Cylinder_4_7.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, -0.323, 12.635]}
						/>
					</group>
					<group
						position={[-259.698, 69.531, 1.998]}
						rotation={[-0.027, 0, -Math.PI / 2]}
					>
						<mesh
							geometry={nodes.Cylinder_1_3.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, -0.323, 12.076]}
						/>
						<mesh
							geometry={nodes.Cylinder_23.geometry}
							material={materials["Black Parts"]}
							position={[-38.177, 2.343, -87.31]}
							rotation={[0, -1.571, 0]}
						/>
						<mesh
							geometry={nodes.Cylinder_2_4.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, 1.175, -43.906]}
						/>
						<mesh
							geometry={nodes.Cylinder_3_5.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, 1.175, -43.347]}
						/>
						<mesh
							geometry={nodes.Cylinder_4_5.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, -0.323, 12.635]}
						/>
					</group>
					<group
						position={[-89.795, -687.401, 5.559]}
						rotation={[-0.027, 0, Math.PI]}
					>
						<mesh
							geometry={nodes.Cylinder_1_2.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, -0.323, 12.076]}
						/>
						<mesh
							geometry={nodes.Cylinder_22.geometry}
							material={materials["Black Parts"]}
							position={[-38.177, 2.343, -87.31]}
							rotation={[0, -1.571, 0]}
						/>
						<mesh
							geometry={nodes.Cylinder_2_3.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, 1.175, -43.906]}
						/>
						<mesh
							geometry={nodes.Cylinder_3_4.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, 1.175, -43.347]}
						/>
						<mesh
							geometry={nodes.Cylinder_4_4.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, -0.323, 12.635]}
						/>
					</group>
					<group
						position={[182.03, -293.587, 1.998]}
						rotation={[-0.027, 0, -Math.PI / 2]}
					>
						<mesh
							geometry={nodes.Cylinder_1_4.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, -0.323, 12.076]}
						/>
						<mesh
							geometry={nodes.Cylinder_24.geometry}
							material={materials["Black Parts"]}
							position={[-38.177, 2.343, -87.31]}
							rotation={[0, -1.571, 0]}
						/>
						<mesh
							geometry={nodes.Cylinder_2_5.geometry}
							material={materials["Black Parts"]}
							position={[-59.323, 1.175, -43.906]}
						/>
						<mesh
							geometry={nodes.Cylinder_3_6.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, 1.175, -43.347]}
						/>
						<mesh
							geometry={nodes.Cylinder_4_6.geometry}
							material={materials["Black Parts"]}
							position={[-20.893, -0.323, 12.635]}
						/>
					</group>
					<group
						position={[-7.202, 368.505, -13.553]}
						rotation={[-0.027, 0, 0]}
					>
						<mesh
							geometry={nodes.Cylinder_1_6.geometry}
							material={materials["Black Parts"]}
							position={[-25.426, 11.967, 19.749]}
						/>
						<mesh
							geometry={nodes.Cylinder_26.geometry}
							material={materials["Black Parts"]}
							position={[-25.426, 12.774, -10.423]}
						/>
						<mesh
							geometry={nodes.Cylinder_6_4.geometry}
							material={materials["Body 1"]}
							position={[-25.426, 12.119, 14.041]}
						/>
					</group>
				</group>
				<group position={[-5.556, 383.459, -340.397]}>
					<mesh
						geometry={nodes.Cube_13_2.geometry}
						material={materials["Black Parts"]}
						position={[-3.348, 4.653, 27.141]}
					/>
				</group>
				<group
					position={[97.759, -140.532, -340.397]}
					rotation={[0, 0, Math.PI]}
				>
					<mesh
						geometry={nodes.Cube_1_3.geometry}
						material={materials["Black Parts"]}
						position={[-3.348, 35.407, 21.09]}
					/>
				</group>
				<group
					position={[260.115, -91.579, -266.742]}
					rotation={[-0.027, 0, Math.PI]}
				>
					<group
						position={[363.941, 556.976, -26.936]}
						rotation={[-0.019, -0.026, -1.543]}
					>
						<mesh
							geometry={nodes.Cylinder_5_23.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[4.818, -197.532, -6.749]}
						rotation={[0, 0, 0.043]}
					>
						<mesh
							geometry={nodes.Cylinder_5_17.geometry}
							material={materials["Black Parts"]}
							position={[4.888, 40.51, -27.26]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[14.967, -363.233, -2.316]}
						rotation={[0, 0, 0.241]}
					>
						<mesh
							geometry={nodes.Cylinder_5_16.geometry}
							material={materials["Black Parts"]}
							position={[4.888, 40.51, -27.26]}
							rotation={[0.656, -0.044, -0.265]}
						/>
					</group>
					<group position={[7.89, -17.576, -11.564]}>
						<mesh
							geometry={nodes.Cylinder_5_18.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[48.481, -505.651, -1.089]}
						rotation={[0, 0, 0.273]}
					>
						<mesh
							geometry={nodes.Cylinder_5_15.geometry}
							material={materials["Black Parts"]}
							position={[4.888, 40.51, -27.26]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group position={[7.89, 156.125, -16.211]}>
						<mesh
							geometry={nodes.Cylinder_5_20.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[34.364, 328.165, -20.814]}
						rotation={[0, 0, -0.175]}
					>
						<mesh
							geometry={nodes.Cylinder_5_19.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[71.303, 499.78, -25.406]}
						rotation={[0, 0, -0.247]}
					>
						<mesh
							geometry={nodes.Cylinder_5_22.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[197.801, -697.792, 4.052]}
						rotation={[-0.097, 0.09, 0.836]}
					>
						<mesh
							geometry={nodes.Cylinder_5_13.geometry}
							material={materials["Black Parts"]}
							position={[4.888, 40.51, -27.26]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[111.439, -612.985, 1.783]}
						rotation={[-0.119, 0.11, 0.857]}
					>
						<mesh
							geometry={nodes.Cylinder_5_14.geometry}
							material={materials["Black Parts"]}
							position={[4.888, 40.51, -27.26]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[171.79, 556.709, -26.929]}
						rotation={[-0.02, -0.026, -1.554]}
					>
						<mesh
							geometry={nodes.Cylinder_5_21.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
				</group>
				<group
					position={[-279.655, -91.579, -266.742]}
					rotation={[3.115, 0, Math.PI]}
					scale={-1}
				>
					<group position={[7.89, -17.576, -11.564]}>
						<mesh
							geometry={nodes.Cylinder_5_9.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[4.818, -197.532, -6.749]}
						rotation={[0, 0, 0.043]}
					>
						<mesh
							geometry={nodes.Cylinder_5_8.geometry}
							material={materials["Black Parts"]}
							position={[4.888, 40.51, -27.26]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[14.967, -363.233, -2.316]}
						rotation={[0, 0, 0.241]}
					>
						<mesh
							geometry={nodes.Cylinder_5_6.geometry}
							material={materials["Black Parts"]}
							position={[4.888, 40.51, -27.26]}
							rotation={[0.656, -0.044, -0.265]}
						/>
					</group>
					<group
						position={[48.481, -505.651, -1.089]}
						rotation={[0, 0, 0.273]}
					>
						<mesh
							geometry={nodes.Cylinder_4_3.geometry}
							material={materials["Black Parts"]}
							position={[3.206, -35.285, -25.166]}
							rotation={[-0.513, -0.058, -0.168]}
						/>
					</group>
					<group position={[7.89, 156.125, -16.211]}>
						<mesh
							geometry={nodes.Cylinder_5_11.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[34.364, 328.165, -20.814]}
						rotation={[0, 0, -0.175]}
					>
						<mesh
							geometry={nodes.Cylinder_5_10.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[71.304, 499.78, -25.406]}
						rotation={[0, 0, -0.247]}
					>
						<mesh
							geometry={nodes.Cylinder_5_12.geometry}
							material={materials["Black Parts"]}
							position={[4.561, 32.955, -10.814]}
							rotation={[0.644, -0.087, -0.265]}
						/>
					</group>
					<group
						position={[197.801, -697.792, 4.052]}
						rotation={[-0.097, 0.09, 0.836]}
					>
						<mesh
							geometry={nodes.Cylinder_2_2.geometry}
							material={materials["Black Parts"]}
							position={[3.206, -35.285, -25.166]}
							rotation={[-0.513, -0.058, -0.168]}
						/>
					</group>
					<group
						position={[111.439, -612.985, 1.783]}
						rotation={[-0.119, 0.11, 0.857]}
					>
						<mesh
							geometry={nodes.Cylinder_3_3.geometry}
							material={materials["Black Parts"]}
							position={[3.206, -35.285, -25.166]}
							rotation={[-0.513, -0.058, -0.168]}
						/>
					</group>
				</group>
				<group position={[-9.401, -403.446, -157.017]}>
					<mesh
						geometry={nodes.Mesh149.geometry}
						material={materials.Redparts}
						receiveShadow
					/>
					<mesh
						geometry={nodes.Mesh149_1.geometry}
						material={materials.Floor}
						receiveShadow
					/>

					{/* <mesh geometry={nodes.Mesh149_1.geometry}>
						<meshBasicMaterial
							colorWrite={false}
							color={"black"}
							transparent={false}
						/>
					</mesh> */}
					<mesh
						geometry={nodes.Mesh149_2.geometry}
						material={materials["Body 1"]}
						receiveShadow
					/>
					<mesh
						geometry={nodes.Mesh149_3.geometry}
						material={materials["Glass.001"]}
					>
						<meshStandardMaterial
							emissiveIntensity={1}
							emissive={"white"}
						/>
					</mesh>
					<mesh
						geometry={nodes.Mesh149_4.geometry}
						material={materials["Black Parts"]}
						castShadow
					/>
					<mesh
						geometry={nodes.Mesh149_5.geometry}
						material={materials.Light}
					/>
					<mesh
						geometry={nodes.Mesh149_6.geometry}
						material={materials["Redparts.001"]}
					/>
					<mesh
						geometry={nodes.Mesh149_7.geometry}
						material={materials.Boat}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/assets/RagingSea/boat.glb");
