/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/assets/IsabellaExplorer/isabella.glb -o features/IsabellaExplorer/components/Model2.tsx -t 
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Lantern from "./Lantern";
import Title from "./Title";
import Monster from "./Monster";

type GLTFResult = GLTF & {
	nodes: {
		Chest001_1: THREE.Mesh;
		Chest001_2: THREE.Mesh;
		Branch_1: THREE.Mesh;
		Branch_2: THREE.Mesh;
		Text002: THREE.Mesh;
		Monster: THREE.Mesh;
		MonsterEyes_1: THREE.Mesh;
		MonsterEyes_2: THREE.Mesh;
		Sphere001: THREE.Mesh;
		Sphere002: THREE.Mesh;
		Scull: THREE.Mesh;
		Rock: THREE.Mesh;
		Rock001: THREE.Mesh;
		Rock002: THREE.Mesh;
		Rock003: THREE.Mesh;
		Body_1: THREE.Mesh;
		Body_2: THREE.Mesh;
		Body_3: THREE.Mesh;
		Body_4: THREE.Mesh;
		Body_5: THREE.Mesh;
		Body_6: THREE.Mesh;
		Body_7: THREE.Mesh;
		Body_8: THREE.Mesh;
		Body_9: THREE.Mesh;
		Body_10: THREE.Mesh;
		Body_11: THREE.Mesh;
		Body_12: THREE.Mesh;
		Body_13: THREE.Mesh;
		Body_14: THREE.Mesh;
		Body_15: THREE.Mesh;
		Body_16: THREE.Mesh;
		Body_17: THREE.Mesh;
		Body_18: THREE.Mesh;
		HairOrigin: THREE.Mesh;
		Lantern_1: THREE.Mesh;
		Lantern_2: THREE.Mesh;
	};
	materials: {
		["Wood.001"]: THREE.MeshStandardMaterial;
		["Bronze.001"]: THREE.MeshStandardMaterial;
		Leaf: THREE.MeshStandardMaterial;
		Text: THREE.MeshStandardMaterial;
		Pupil: THREE.MeshStandardMaterial;
		Material: THREE.MeshStandardMaterial;
		Body: THREE.MeshStandardMaterial;
		White: THREE.MeshStandardMaterial;
		BG: THREE.MeshStandardMaterial;
		["Body.001"]: THREE.MeshStandardMaterial;
		Eye: THREE.MeshStandardMaterial;
		Iris: THREE.MeshStandardMaterial;
		Cloth: THREE.MeshStandardMaterial;
		Shirt: THREE.MeshStandardMaterial;
		Boots: THREE.MeshStandardMaterial;
		["Lether.001"]: THREE.MeshStandardMaterial;
		Silver: THREE.MeshStandardMaterial;
		Lether: THREE.MeshStandardMaterial;
		["Cloth.001"]: THREE.MeshStandardMaterial;
		Bronze: THREE.MeshStandardMaterial;
		Gold: THREE.MeshStandardMaterial;
		Hair: THREE.MeshStandardMaterial;
		["Lashes.001"]: THREE.MeshStandardMaterial;
		["Eyebrow.001"]: THREE.MeshStandardMaterial;
		Lantern: THREE.MeshStandardMaterial;
		Glass: THREE.MeshPhysicalMaterial;
	};
	animations: GLTFAction[];
};

export type ActionName = "Animation";
export interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>(null);
	const { nodes, materials, animations } = useGLTF(
		"/assets/IsabellaExplorer/isabella.glb"
	) as GLTFResult;
	const { actions } = useAnimations(animations, group);

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
		>
			<group name="Scene">
				<group
					name="Chest001"
					position={[-0.508, 0, -0.808]}
					rotation={[-Math.PI, 0.293, -Math.PI]}
				>
					<mesh
						name="Chest001_1"
						geometry={nodes.Chest001_1.geometry}
						material={materials["Wood.001"]}
					/>
					<mesh
						name="Chest001_2"
						geometry={nodes.Chest001_2.geometry}
						material={materials["Bronze.001"]}
					/>
				</group>

				<mesh
					name="Scull"
					geometry={nodes.Scull.geometry}
					material={materials.White}
					position={[-0.036, 0.118, -0.371]}
					rotation={[-0.431, -0.405, -0.179]}
				/>
				<mesh
					name="Rock"
					geometry={nodes.Rock.geometry}
					material={materials.BG}
					position={[-1.124, 0, 0.213]}
				/>
				<mesh
					name="Rock001"
					geometry={nodes.Rock001.geometry}
					material={materials.BG}
					position={[0.789, -0.049, -0.821]}
					rotation={[-Math.PI, 0, 0]}
				/>
				<mesh
					name="Rock002"
					geometry={nodes.Rock002.geometry}
					material={materials.BG}
					position={[0.279, -0.187, -0.165]}
					rotation={[-1.143, 0.857, 2.515]}
				/>
				<mesh
					name="Rock003"
					geometry={nodes.Rock003.geometry}
					material={materials.BG}
					position={[-0.67, -0.06, 0.733]}
					rotation={[3.131, 0.152, 0.313]}
					scale={0.5}
				/>
				<group
					name="Body"
					rotation={[0, Math.PI / 6, 0]}
				>
					<mesh
						name="Body_1"
						geometry={nodes.Body_1.geometry}
						material={materials.Body}
					/>
					<mesh
						name="Body_2"
						geometry={nodes.Body_2.geometry}
						material={materials["Body.001"]}
					/>
					<mesh
						name="Body_3"
						geometry={nodes.Body_3.geometry}
						material={materials.Eye}
					/>
					<mesh
						name="Body_4"
						geometry={nodes.Body_4.geometry}
						material={materials.Iris}
					/>
					<mesh
						name="Body_5"
						geometry={nodes.Body_5.geometry}
						material={materials.Pupil}
					/>
					<mesh
						name="Body_6"
						geometry={nodes.Body_6.geometry}
						material={materials.Cloth}
					/>
					<mesh
						name="Body_7"
						geometry={nodes.Body_7.geometry}
						material={materials.Shirt}
					/>
					<mesh
						name="Body_8"
						geometry={nodes.Body_8.geometry}
						material={materials.Boots}
					/>
					<mesh
						name="Body_9"
						geometry={nodes.Body_9.geometry}
						material={materials["Lether.001"]}
					/>
					<mesh
						name="Body_10"
						geometry={nodes.Body_10.geometry}
						material={materials.Silver}
					/>
					<mesh
						name="Body_11"
						geometry={nodes.Body_11.geometry}
						material={materials.Lether}
					/>
					<mesh
						name="Body_12"
						geometry={nodes.Body_12.geometry}
						material={materials["Cloth.001"]}
					/>
					<mesh
						name="Body_13"
						geometry={nodes.Body_13.geometry}
						material={materials.Bronze}
					/>
					<mesh
						name="Body_14"
						geometry={nodes.Body_14.geometry}
						material={materials.Gold}
					/>
					<mesh
						name="Body_15"
						geometry={nodes.Body_15.geometry}
						material={materials.White}
					/>
					<mesh
						name="Body_16"
						geometry={nodes.Body_16.geometry}
						material={materials.Hair}
					/>
					<mesh
						name="Body_17"
						geometry={nodes.Body_17.geometry}
						material={materials["Lashes.001"]}
					/>
					<mesh
						name="Body_18"
						geometry={nodes.Body_18.geometry}
						material={materials["Eyebrow.001"]}
					/>
				</group>
				<mesh
					name="HairOrigin"
					geometry={nodes.HairOrigin.geometry}
					material={materials.Hair}
					position={[0.044, 1.696, 0.049]}
					rotation={[0.672, 0.212, -0.497]}
				/>
				<Lantern
					nodes={nodes}
					materials={materials}
					rotation={[0, Math.PI / 6, 0]}
					position={[-0.273, 1.546, 0.461]}
				/>

				<Title
					nodes={nodes}
					materials={materials}
				/>
				<Monster
					nodes={nodes}
					materials={materials}
					actions={actions}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/assets/IsabellaExplorer/isabella.glb");
