/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/assets/PocketmonsterPortals/models/Dragon_Evolved.gltf -o ./features/PocketmonsterPortals/components/DragonModel.tsx -t 
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import useStore from "../../store/useStore";

type GLTFResult = GLTF & {
	nodes: {
		Cube221: THREE.SkinnedMesh;
		Cube221_1: THREE.SkinnedMesh;
		Cube221_2: THREE.SkinnedMesh;
		Cube221_3: THREE.SkinnedMesh;
		Cube221_4: THREE.SkinnedMesh;
		Root: THREE.Bone;
	};
	materials: {
		Dragon_Main: THREE.MeshStandardMaterial;
		Dragon_Secondary: THREE.MeshStandardMaterial;
		Dragon_Horn: THREE.MeshStandardMaterial;
		Eye_Black: THREE.MeshStandardMaterial;
		Eye_White: THREE.MeshStandardMaterial;
	};
};

type ActionName =
	| "Death"
	| "Fast_Flying"
	| "Flying_Idle"
	| "Headbutt"
	| "HitReact"
	| "No"
	| "Punch"
	| "Yes";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<
		JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
	>
>;

export function DragonModel(props: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>(null);
	const { name } = props;

	const { nodes, materials, animations } = useGLTF(
		"/assets/PocketmonsterPortals/models/Dragon_Evolved.gltf"
	) as GLTFResult;
	const { actions } = useAnimations(animations, group);

	const prevAnimationRef = useRef<string | null>();

	useEffect(() => {
		const unsubscribe = useStore.subscribe(
			(state) => state.hovered,
			(hovered) => {
				const isHovered = hovered === name;

				if (
					isHovered ||
					(!hovered && prevAnimationRef.current !== "Flying_Idle")
				) {
					const action = isHovered ? "Headbutt" : "Flying_Idle";

					if (prevAnimationRef.current) {
						actions[prevAnimationRef.current]?.fadeOut(0.5);
					}

					actions[action]?.reset().fadeIn(0.5).play();
					prevAnimationRef.current = action;
				}
			},
			{ fireImmediately: true }
		);

		return () => {
			unsubscribe();
		};
	}, [actions, name]);

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
		>
			<group name="Scene">
				<group name="CharacterArmature">
					<primitive object={nodes.Root} />
					<group name="Dragon">
						<skinnedMesh
							name="Cube221"
							geometry={nodes.Cube221.geometry}
							material={materials.Dragon_Main}
							skeleton={nodes.Cube221.skeleton}
						/>
						<skinnedMesh
							name="Cube221_1"
							geometry={nodes.Cube221_1.geometry}
							material={materials.Dragon_Secondary}
							skeleton={nodes.Cube221_1.skeleton}
						/>
						<skinnedMesh
							name="Cube221_2"
							geometry={nodes.Cube221_2.geometry}
							material={materials.Dragon_Horn}
							skeleton={nodes.Cube221_2.skeleton}
						/>
						<skinnedMesh
							name="Cube221_3"
							geometry={nodes.Cube221_3.geometry}
							material={materials.Eye_Black}
							skeleton={nodes.Cube221_3.skeleton}
						/>
						<skinnedMesh
							name="Cube221_4"
							geometry={nodes.Cube221_4.geometry}
							material={materials.Eye_White}
							skeleton={nodes.Cube221_4.skeleton}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/assets/PocketmonsterPortals/models/Dragon_Evolved.gltf");
