/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/assets/Cloud69Scene/cloud69.glb -o features/Cloud69Scene/components/Cloud69.tsx -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Float, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
	nodes: {
		RockIsland_1: THREE.Mesh;
		RockIsland_2: THREE.Mesh;
		FirstFloorWindow_1: THREE.Mesh;
		FirstFloorWindow_2: THREE.Mesh;
		FirstFloorDoor: THREE.Mesh;
		MainBuildingLightStripes: THREE.Mesh;
		PumpRoofStripes: THREE.Mesh;
		Building_1: THREE.Mesh;
		Building_2: THREE.Mesh;
		Building_3: THREE.Mesh;
		Building_4: THREE.Mesh;
		Building_5: THREE.Mesh;
		Building_6: THREE.Mesh;
		SignStripes: THREE.Mesh;
		PumpsBase_1: THREE.Mesh;
		PumpsBase_2: THREE.Mesh;
		WindowCovers: THREE.Mesh;
		Tent_1: THREE.Mesh;
		Tent_2: THREE.Mesh;
		Tent_3: THREE.Mesh;
		Plane027: THREE.Mesh;
		Plane027_1: THREE.Mesh;
		Propeler: THREE.Mesh;
		ArrowBase_1: THREE.Mesh;
		ArrowBase_2: THREE.Mesh;
		ArrowBase_3: THREE.Mesh;
		ArrowOutline: THREE.Mesh;
		Arrows001: THREE.Mesh;
		Arrows002: THREE.Mesh;
		Arrows003: THREE.Mesh;
		Arrows004: THREE.Mesh;
		Arrows005: THREE.Mesh;
		Arrows006: THREE.Mesh;
		ArrowSign: THREE.Mesh;
		Pumps_1: THREE.Mesh;
		Pumps_2: THREE.Mesh;
		Pumps_3: THREE.Mesh;
		Tubes: THREE.Mesh;
		TubeMain: THREE.Mesh;
		Frame_1: THREE.Mesh;
		Frame_2: THREE.Mesh;
		TankCluster001_1: THREE.Mesh;
		TankCluster001_2: THREE.Mesh;
		TankCluster001_3: THREE.Mesh;
		TankCluster001_4: THREE.Mesh;
		TankCluster002_1: THREE.Mesh;
		TankCluster002_2: THREE.Mesh;
		TankCluster002_3: THREE.Mesh;
		TankCluster_1: THREE.Mesh;
		TankCluster_2: THREE.Mesh;
		["69SignText"]: THREE.Mesh;
		CloudSignText: THREE.Mesh;
		BarText: THREE.Mesh;
		PumpText: THREE.Mesh;
		MarketText: THREE.Mesh;
		Bilboard_1: THREE.Mesh;
		Bilboard_2: THREE.Mesh;
		Bilboard_3: THREE.Mesh;
		BuildbordText: THREE.Mesh;
		Barrels: THREE.Mesh;
		Tires: THREE.Mesh;
		Trashcan_1: THREE.Mesh;
		Trashcan_2: THREE.Mesh;
		Trashcan_3: THREE.Mesh;
		Trashcan001_1: THREE.Mesh;
		Trashcan001_2: THREE.Mesh;
		Trashcan001_3: THREE.Mesh;
		["Vending-machine_1"]: THREE.Mesh;
		["Vending-machine_2"]: THREE.Mesh;
		["Vending-machine_3"]: THREE.Mesh;
		Streetlamp_1: THREE.Mesh;
		Streetlamp_2: THREE.Mesh;
		Streetlamp_3: THREE.Mesh;
		Streetlamp_4: THREE.Mesh;
		Streetlamp_5: THREE.Mesh;
		Streetpole: THREE.Mesh;
		Cables: THREE.Mesh;
		WarningLight_1: THREE.Mesh;
		WarningLight_2: THREE.Mesh;
		SecondFloorWindow: THREE.Mesh;
		Car_1: THREE.Mesh;
		Car_2: THREE.Mesh;
		CarFrontLights: THREE.Mesh;
		CarTailLights: THREE.Mesh;
		CarTanks_1: THREE.Mesh;
		CarTanks_2: THREE.Mesh;
		CarWindows: THREE.Mesh;
		Engines_1: THREE.Mesh;
		Engines_2: THREE.Mesh;
		Engines_3: THREE.Mesh;
	};
	materials: {
		Ground: THREE.MeshStandardMaterial;
		Concrete: THREE.MeshStandardMaterial;
		Metal: THREE.MeshStandardMaterial;
		WindowLight: THREE.MeshStandardMaterial;
		["Neon.001"]: THREE.MeshStandardMaterial;
		MetalBlue: THREE.MeshStandardMaterial;
		Wall: THREE.MeshStandardMaterial;
		Wood: THREE.MeshStandardMaterial;
		["Metal.002"]: THREE.MeshStandardMaterial;
		Neon: THREE.MeshStandardMaterial;
		White: THREE.MeshStandardMaterial;
		Red: THREE.MeshStandardMaterial;
		["Metal.001"]: THREE.MeshStandardMaterial;
		WarningLight: THREE.MeshStandardMaterial;
		Rubber: THREE.MeshStandardMaterial;
		Chrome: THREE.MeshStandardMaterial;
		["Metal.003"]: THREE.MeshStandardMaterial;
		Cardboard: THREE.MeshStandardMaterial;
		Lamp: THREE.MeshStandardMaterial;
		TrafficGreen: THREE.MeshPhysicalMaterial;
		TrafficOrange: THREE.MeshPhysicalMaterial;
		TrafficRed: THREE.MeshStandardMaterial;
		HeadLights: THREE.MeshStandardMaterial;
		TailLights: THREE.MeshStandardMaterial;
		Window: THREE.MeshStandardMaterial;
		NeonEngine: THREE.MeshStandardMaterial;
	};
};

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Cloud69(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/assets/Cloud69Scene/cloud69.glb"
	) as GLTFResult;

	const propellerRef = useRef<THREE.Mesh>(null);
	const warningLIgh1Ref = useRef<THREE.Mesh>(null);
	const arrowsRef = useRef<THREE.Group>(null);
	const lightRef = useRef<THREE.PointLight>(null);
	const lampRef = useRef<THREE.Mesh>(null);

	useFrame(({ clock: { elapsedTime }, camera }, delta) => {
		if (propellerRef.current) {
			propellerRef.current.rotation.y += delta * 2;
		}

		if (arrowsRef.current) {
			arrowsRef.current.children.forEach((child, idx) => {
				if (child instanceof THREE.Mesh) {
					child.visible = Math.floor(elapsedTime * 2) % 6 !== idx;
				}
			});
		}

		if (
			warningLIgh1Ref.current &&
			"emissiveIntensity" in warningLIgh1Ref.current.material
		) {
			warningLIgh1Ref.current.material.emissiveIntensity =
				Math.sin(elapsedTime * 5) * 24;
		}

		if (
			lightRef.current &&
			lampRef.current &&
			"emissiveIntensity" in lampRef.current.material
		) {
			const normalIntensity = 2;
			const normalEmmision = 50;
			const probability = Math.random() * 10;

			if (probability < 1) {
				const randomStrength = Math.random();
				lightRef.current.intensity = normalIntensity * randomStrength;
				lampRef.current.material.emissiveIntensity =
					normalEmmision * randomStrength;
			} else {
				lightRef.current.intensity = normalIntensity;
				lampRef.current.material.emissiveIntensity = normalEmmision;
			}
		}
	});

	return (
		<group
			{...props}
			dispose={null}
		>
			<pointLight
				ref={lightRef}
				intensity={3}
				position={[-0.4, 2.2, 1.4]}
			/>
			<group position={[3.302, 0, -0.755]}>
				<mesh
					geometry={nodes.RockIsland_1.geometry}
					material={materials.Ground}
				/>
				<mesh
					geometry={nodes.RockIsland_2.geometry}
					material={materials.Concrete}
					receiveShadow
				/>
			</group>
			<group position={[-1.799, 0.1, -0.976]}>
				<mesh
					geometry={nodes.FirstFloorWindow_1.geometry}
					material={materials.Metal}
				/>
				<mesh
					geometry={nodes.FirstFloorWindow_2.geometry}
					material={materials.WindowLight}
				/>
			</group>
			<mesh
				geometry={nodes.FirstFloorDoor.geometry}
				material={materials.Metal}
				position={[-1.799, 0.1, -0.976]}
			/>
			<mesh
				geometry={nodes.MainBuildingLightStripes.geometry}
				material={materials["Neon.001"]}
				position={[-1.799, 0.1, -0.976]}
			/>
			<mesh
				geometry={nodes.PumpRoofStripes.geometry}
				material={materials["Neon.001"]}
				position={[-1.799, 0.1, -0.976]}
			/>
			<group
				position={[-1.362, 1.381, 1.158]}
				scale={0.254}
			>
				<mesh
					geometry={nodes.Building_1.geometry}
					material={materials.Concrete}
					receiveShadow
					castShadow
				/>
				<mesh
					geometry={nodes.Building_2.geometry}
					material={materials.MetalBlue}
					receiveShadow
				/>
				<mesh
					geometry={nodes.Building_3.geometry}
					material={materials["Neon.001"]}
				/>
				<mesh
					geometry={nodes.Building_4.geometry}
					material={materials.Wall}
				/>
				<mesh
					geometry={nodes.Building_5.geometry}
					material={materials.Wood}
					receiveShadow
					castShadow
				/>
				<mesh
					geometry={nodes.Building_6.geometry}
					material={materials["Metal.002"]}
					receiveShadow
					castShadow
				/>
			</group>
			<mesh
				geometry={nodes.SignStripes.geometry}
				material={materials["Neon.001"]}
				position={[-1.977, 1.2, 2.207]}
			/>
			<group position={[-1.805, 0.1, 2.37]}>
				<mesh
					geometry={nodes.PumpsBase_1.geometry}
					material={materials.Concrete}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.PumpsBase_2.geometry}
					material={materials.Neon}
				/>
			</group>
			<mesh
				geometry={nodes.WindowCovers.geometry}
				material={materials.Wood}
				position={[-2.081, 1.642, -1.73]}
			/>
			<group position={[-1.961, 1.642, -0.824]}>
				<mesh
					geometry={nodes.Tent_1.geometry}
					material={materials.Wood}
				/>
				<mesh
					geometry={nodes.Tent_2.geometry}
					material={materials.White}
					receiveShadow
				/>
				<mesh
					geometry={nodes.Tent_3.geometry}
					material={materials.Red}
					receiveShadow
				/>
			</group>
			<group position={[1.132, 0.1, -0.964]}>
				<mesh
					geometry={nodes.Plane027.geometry}
					material={materials["Metal.002"]}
				/>
				<mesh
					geometry={nodes.Plane027_1.geometry}
					material={materials.Neon}
				/>
				<mesh
					ref={propellerRef}
					geometry={nodes.Propeler.geometry}
					material={materials["Metal.001"]}
					position={[0, 0.687, 0]}
				/>
			</group>
			<group position={[3.287, 0.003, -0.763]}>
				<mesh
					geometry={nodes.ArrowBase_1.geometry}
					material={materials.Concrete}
					castShadow
				/>
				<mesh
					geometry={nodes.ArrowBase_2.geometry}
					material={materials["Metal.002"]}
					castShadow
				/>
				<mesh
					ref={warningLIgh1Ref}
					geometry={nodes.ArrowBase_3.geometry}
					material={materials.WarningLight}
				/>
				<mesh
					geometry={nodes.ArrowOutline.geometry}
					material={materials["Neon.001"]}
					position={[0.107, 0.701, -0.041]}
				/>
				<group ref={arrowsRef}>
					<mesh
						geometry={nodes.Arrows001.geometry}
						material={materials["Neon.001"]}
						position={[-0.265, 0.701, 0.045]}
					/>
					<mesh
						geometry={nodes.Arrows002.geometry}
						material={materials["Neon.001"]}
						position={[-0.265, 0.701, 0.045]}
					/>
					<mesh
						geometry={nodes.Arrows003.geometry}
						material={materials["Neon.001"]}
						position={[-0.265, 0.701, 0.045]}
					/>
					<mesh
						geometry={nodes.Arrows004.geometry}
						material={materials["Neon.001"]}
						position={[-0.265, 0.701, 0.045]}
					/>
					<mesh
						geometry={nodes.Arrows005.geometry}
						material={materials["Neon.001"]}
						position={[-0.265, 0.701, 0.045]}
					/>
					<mesh
						geometry={nodes.Arrows006.geometry}
						material={materials["Neon.001"]}
						position={[-0.265, 0.701, 0.045]}
					/>
				</group>

				<mesh
					geometry={nodes.ArrowSign.geometry}
					material={materials.Rubber}
					position={[0.107, 0.701, -0.041]}
				/>
			</group>
			<group
				position={[-2.478, 0.531, 2.208]}
				scale={[1.458, 1, 1]}
			>
				<mesh
					geometry={nodes.Pumps_1.geometry}
					material={materials.Metal}
				/>
				<mesh
					geometry={nodes.Pumps_2.geometry}
					material={materials.Red}
				/>
				<mesh
					geometry={nodes.Pumps_3.geometry}
					material={materials.MetalBlue}
				/>
			</group>
			<mesh
				geometry={nodes.Tubes.geometry}
				material={materials.Chrome}
				position={[1.82, 0.1, -0.764]}
				castShadow
			/>
			<mesh
				geometry={nodes.TubeMain.geometry}
				material={materials["Metal.001"]}
				position={[1.137, 0.407, -0.455]}
				receiveShadow
			/>
			<group position={[-1.176, 0.005, 1.651]}>
				<mesh
					geometry={nodes.Frame_1.geometry}
					material={materials["Metal.001"]}
					receiveShadow
				/>
				<mesh
					geometry={nodes.Frame_2.geometry}
					material={materials["Metal.002"]}
					receiveShadow
				/>
			</group>
			<group
				position={[-1.396, -1.601, -1.125]}
				rotation={[2.196, 0, -1.571]}
				scale={0.394}
			>
				<mesh
					geometry={nodes.TankCluster001_1.geometry}
					material={materials["Metal.001"]}
				/>
				<mesh
					geometry={nodes.TankCluster001_2.geometry}
					material={materials["Metal.002"]}
				/>
				<mesh
					geometry={nodes.TankCluster001_3.geometry}
					material={materials.Metal}
				/>
				<mesh
					geometry={nodes.TankCluster001_4.geometry}
					material={materials["Metal.003"]}
				/>
			</group>
			<group
				position={[-1.411, -0.004, 2.288]}
				rotation={[Math.PI, 1.571, 0]}
				scale={[0.628, 0.628, 0.561]}
			>
				<mesh
					geometry={nodes.TankCluster002_1.geometry}
					material={materials["Metal.001"]}
				/>
				<mesh
					geometry={nodes.TankCluster002_2.geometry}
					material={materials["Metal.002"]}
				/>
				<mesh
					geometry={nodes.TankCluster002_3.geometry}
					material={materials.Metal}
				/>
			</group>
			<group
				position={[0.953, -0.45, -1.203]}
				rotation={[0, -1.571, 0]}
				scale={0.85}
			>
				<mesh
					geometry={nodes.TankCluster_1.geometry}
					material={materials.Metal}
				/>
				<mesh
					geometry={nodes.TankCluster_2.geometry}
					material={materials["Metal.001"]}
				/>
			</group>
			<mesh
				geometry={nodes["69SignText"].geometry}
				material={materials.Neon}
				position={[-1.822, 2.169, 2.238]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={0.812}
			/>
			<mesh
				geometry={nodes.CloudSignText.geometry}
				material={materials["Neon.001"]}
				position={[-1.822, 2.648, 2.282]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={0.624}
			/>
			<mesh
				geometry={nodes.BarText.geometry}
				material={materials["Neon.001"]}
				position={[-0.96, 2.648, -1.299]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={0.711}
			/>
			<mesh
				geometry={nodes.PumpText.geometry}
				material={materials.Neon}
				position={[-0.851, 1.312, 1.057]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={0.225}
			/>
			<mesh
				geometry={nodes.MarketText.geometry}
				material={materials["Neon.001"]}
				position={[-1.912, 1.518, 0.073]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.225}
			/>
			<group
				position={[-1.943, 4.39, -1.3]}
				rotation={[Math.PI / 2, 0, 0]}
			>
				<mesh
					geometry={nodes.Bilboard_1.geometry}
					material={materials["Metal.001"]}
					castShadow
				/>
				<mesh
					geometry={nodes.Bilboard_2.geometry}
					material={materials["Neon.001"]}
				/>
				<mesh
					geometry={nodes.Bilboard_3.geometry}
					material={materials["Metal.002"]}
				/>
			</group>

			<mesh
				geometry={nodes.BuildbordText.geometry}
				material={materials.Neon}
				position={[-1.95, 4.435, -1.284]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.57}
			/>
			<mesh
				geometry={nodes.Barrels.geometry}
				material={materials.Metal}
				position={[-0.417, 0.1, 2.746]}
				rotation={[0, 1.426, 0]}
				scale={0.489}
			/>
			<mesh
				geometry={nodes.Tires.geometry}
				material={materials.Rubber}
				position={[-0.728, 0.1, 3.06]}
				rotation={[0, -0.274, -0.022]}
				scale={0.455}
			/>
			<group
				position={[-3.431, 1.654, -0.507]}
				rotation={[Math.PI, -1.134, Math.PI]}
				scale={0.52}
			>
				<mesh
					geometry={nodes.Trashcan_1.geometry}
					material={materials.Metal}
					castShadow
				/>
				<mesh
					geometry={nodes.Trashcan_2.geometry}
					material={materials.White}
				/>
				<mesh
					geometry={nodes.Trashcan_3.geometry}
					material={materials.Cardboard}
				/>
			</group>
			<group
				position={[0.653, 0.1, -2.235]}
				rotation={[-Math.PI, 1.536, -Math.PI]}
				scale={0.432}
			>
				<mesh
					geometry={nodes.Trashcan001_1.geometry}
					material={materials.Metal}
					castShadow
				/>
				<mesh
					geometry={nodes.Trashcan001_2.geometry}
					material={materials.White}
				/>
				<mesh
					geometry={nodes.Trashcan001_3.geometry}
					material={materials.Cardboard}
				/>
			</group>
			<group
				position={[-1.006, 0.1, 0.075]}
				scale={0.429}
			>
				<mesh
					geometry={nodes["Vending-machine_1"].geometry}
					material={materials.Red}
				/>
				<mesh
					geometry={nodes["Vending-machine_2"].geometry}
					material={materials.Neon}
				/>
				<mesh
					geometry={nodes["Vending-machine_3"].geometry}
					material={materials.Rubber}
				/>
			</group>
			<group
				position={[-0.407, 0.1, 2.035]}
				rotation={[0, Math.PI / 2, 0]}
				scale={0.384}
			>
				<mesh
					geometry={nodes.Streetlamp_1.geometry}
					material={materials["Metal.002"]}
					castShadow
				/>
				<mesh
					ref={lampRef}
					geometry={nodes.Streetlamp_2.geometry}
					material={materials.Lamp}
				/>
				<mesh
					geometry={nodes.Streetlamp_3.geometry}
					material={materials.TrafficGreen}
				/>
				<mesh
					geometry={nodes.Streetlamp_4.geometry}
					material={materials.TrafficOrange}
				/>
				<mesh
					geometry={nodes.Streetlamp_5.geometry}
					material={materials.TrafficRed}
				/>
			</group>
			<mesh
				geometry={nodes.Streetpole.geometry}
				material={materials.Wood}
				position={[-3.419, 1.642, -2.467]}
				rotation={[0, Math.PI / 2, 0]}
				scale={0.714}
				castShadow
			/>
			<mesh
				geometry={nodes.Cables.geometry}
				material={materials.Rubber}
				castShadow
			/>
			<group
				position={[2.776, -0.005, 1.758]}
				rotation={[0, 0, -Math.PI / 2]}
			>
				<mesh
					geometry={nodes.WarningLight_1.geometry}
					material={materials["Metal.002"]}
				/>
				<mesh
					geometry={nodes.WarningLight_2.geometry}
					material={materials.WarningLight}
				/>
			</group>
			<mesh
				geometry={nodes.SecondFloorWindow.geometry}
				material={materials.WindowLight}
				position={[-1.362, 1.381, 1.158]}
				scale={0.254}
			/>
			<Float>
				<group
					position={[0.39, -0.222, 0.951]}
					rotation={[0, -Math.PI / 2, 0]}
					scale={0.58}
				>
					<mesh
						geometry={nodes.Car_1.geometry}
						material={materials.Red}
						receiveShadow
					/>
					<mesh
						geometry={nodes.Car_2.geometry}
						material={materials.Chrome}
					/>
					<mesh
						geometry={nodes.CarFrontLights.geometry}
						material={materials.HeadLights}
					/>
					<mesh
						geometry={nodes.CarTailLights.geometry}
						material={materials.TailLights}
					/>
					<group
						position={[0.451, 0.243, 1.239]}
						rotation={[0.945, 0, 1.571]}
						scale={0.2}
					>
						<mesh
							geometry={nodes.CarTanks_1.geometry}
							material={materials["Metal.001"]}
						/>
						<mesh
							geometry={nodes.CarTanks_2.geometry}
							material={materials.Metal}
						/>
					</group>
					<mesh
						geometry={nodes.CarWindows.geometry}
						material={materials.Window}
					/>
					<group position={[0, 0, 0.101]}>
						<mesh
							geometry={nodes.Engines_1.geometry}
							material={materials.Metal}
						/>
						<mesh
							geometry={nodes.Engines_2.geometry}
							material={materials.NeonEngine}
						/>
						<mesh
							geometry={nodes.Engines_3.geometry}
							material={materials.Neon}
						/>
					</group>
				</group>
			</Float>
		</group>
	);
}

useGLTF.preload("/assets/Cloud69Scene/cloud69.glb");
