/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ../../../public/assets/Mesmerized3d/camping.glb -t -k -K 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import OverlayItem from "./OverlayItem";
import { degToRad } from "three/src/math/MathUtils.js";

type GLTFResult = GLTF & {
	nodes: {
		group330264743: THREE.Mesh;
		group756785519: THREE.Mesh;
		group1592954421: THREE.Mesh;
		group1997237509: THREE.Mesh;
		group1774949739: THREE.Mesh;
		group912174311: THREE.Mesh;
		group2003861280: THREE.Mesh;
		group312988249: THREE.Mesh;
		group1139254300: THREE.Mesh;
		group611470674: THREE.Mesh;
		group1725671573: THREE.Mesh;
		group1910173211: THREE.Mesh;
		group467729922: THREE.Mesh;
		group648914745: THREE.Mesh;
		group1726783281: THREE.Mesh;
		group213706146: THREE.Mesh;
		group2084766983: THREE.Mesh;
		group637283230: THREE.Mesh;
		group625022612: THREE.Mesh;
		group799625953: THREE.Mesh;
		group1241182310: THREE.Mesh;
		group1762625985: THREE.Mesh;
		group2016668438: THREE.Mesh;
		group1211270279: THREE.Mesh;
		group962132412: THREE.Mesh;
		group2045238674: THREE.Mesh;
		group2034554043: THREE.Mesh;
		group1249314938: THREE.Mesh;
		tent: THREE.Mesh;
		group612170013: THREE.Mesh;
		group1726941988: THREE.Mesh;
		group535548886: THREE.Mesh;
		group1834474229: THREE.Mesh;
		group1828253948: THREE.Mesh;
		group1083046558: THREE.Mesh;
		group1173642836: THREE.Mesh;
		group1354684915: THREE.Mesh;
		group179715504: THREE.Mesh;
		group870377423: THREE.Mesh;
		group2051321267: THREE.Mesh;
		group537140664: THREE.Mesh;
		group1931903066: THREE.Mesh;
		group81696465: THREE.Mesh;
		group1952052079: THREE.Mesh;
		group868215323: THREE.Mesh;
		group965679006: THREE.Mesh;
		group2126162799: THREE.Mesh;
		group1146075737: THREE.Mesh;
		group1374130805: THREE.Mesh;
		group903640800: THREE.Mesh;
		group1075032789: THREE.Mesh;
		group774324054: THREE.Mesh;
		group1484014363: THREE.Mesh;
		group511150639: THREE.Mesh;
		group2137964724: THREE.Mesh;
		group1541698971: THREE.Mesh;
		group1188624501: THREE.Mesh;
		mesh663504923: THREE.Mesh;
		mesh663504923_1: THREE.Mesh;
		mesh663504923_2: THREE.Mesh;
		mesh1088612588: THREE.Mesh;
		mesh1088612588_1: THREE.Mesh;
		mesh1088612588_2: THREE.Mesh;
		group1193226793: THREE.Mesh;
		group460129575: THREE.Mesh;
		mesh1434122196: THREE.Mesh;
		mesh1434122196_1: THREE.Mesh;
		mesh1511301575: THREE.Mesh;
		mesh1511301575_1: THREE.Mesh;
		mesh632722702: THREE.Mesh;
		mesh632722702_1: THREE.Mesh;
		mesh1952899948: THREE.Mesh;
		mesh1952899948_1: THREE.Mesh;
		mesh1952899948_2: THREE.Mesh;
		mesh954393760: THREE.Mesh;
		mesh954393760_1: THREE.Mesh;
		mesh954393760_2: THREE.Mesh;
		mesh811728704: THREE.Mesh;
		mesh811728704_1: THREE.Mesh;
		mesh470834711: THREE.Mesh;
		mesh470834711_1: THREE.Mesh;
		mesh981371949: THREE.Mesh;
		mesh981371949_1: THREE.Mesh;
		mesh897427996: THREE.Mesh;
		mesh897427996_1: THREE.Mesh;
		mesh624108358: THREE.Mesh;
		mesh624108358_1: THREE.Mesh;
		mesh595478641: THREE.Mesh;
		mesh595478641_1: THREE.Mesh;
		group2033909409: THREE.Mesh;
		mesh947843091: THREE.Mesh;
		mesh947843091_1: THREE.Mesh;
		mesh1774266040: THREE.Mesh;
		mesh1774266040_1: THREE.Mesh;
		mesh1806860140: THREE.Mesh;
		mesh1806860140_1: THREE.Mesh;
		mesh1806860140_2: THREE.Mesh;
		group1936711080: THREE.Mesh;
		group76132093: THREE.Mesh;
		group1215832014: THREE.Mesh;
		group179033160: THREE.Mesh;
		mesh812894768: THREE.Mesh;
		mesh812894768_1: THREE.Mesh;
		mesh812894768_2: THREE.Mesh;
		mesh812894768_3: THREE.Mesh;
		mesh812894768_4: THREE.Mesh;
		mesh1806556219: THREE.Mesh;
		mesh1806556219_1: THREE.Mesh;
		mesh1806556219_2: THREE.Mesh;
		mesh550750859: THREE.Mesh;
		mesh550750859_1: THREE.Mesh;
		mesh550750859_2: THREE.Mesh;
		mesh137140296: THREE.Mesh;
		mesh137140296_1: THREE.Mesh;
		mesh137140296_2: THREE.Mesh;
		mesh1119639877: THREE.Mesh;
		mesh1119639877_1: THREE.Mesh;
		mesh1119639877_2: THREE.Mesh;
		mesh1121833705: THREE.Mesh;
		mesh1121833705_1: THREE.Mesh;
		mesh1121833705_2: THREE.Mesh;
		group862771831: THREE.Mesh;
		mesh906174970: THREE.Mesh;
		mesh906174970_1: THREE.Mesh;
		mesh906174970_2: THREE.Mesh;
		group1352282937: THREE.Mesh;
		mesh1530965799: THREE.Mesh;
		mesh1530965799_1: THREE.Mesh;
		mesh1530965799_2: THREE.Mesh;
		mesh1838836646: THREE.Mesh;
		mesh1838836646_1: THREE.Mesh;
		mesh1204561430: THREE.Mesh;
		mesh1204561430_1: THREE.Mesh;
		mesh1204561430_2: THREE.Mesh;
		mesh416585231: THREE.Mesh;
		mesh416585231_1: THREE.Mesh;
		mesh416585231_2: THREE.Mesh;
		mesh889152651: THREE.Mesh;
		mesh889152651_1: THREE.Mesh;
		mesh889152651_2: THREE.Mesh;
		mesh1364602715: THREE.Mesh;
		mesh1364602715_1: THREE.Mesh;
		mesh1364602715_2: THREE.Mesh;
		group587165587: THREE.Mesh;
		group1903258221: THREE.Mesh;
		group1992484385: THREE.Mesh;
		group1017972466: THREE.Mesh;
		group1894462670: THREE.Mesh;
		group458100224: THREE.Mesh;
		group1090731226: THREE.Mesh;
		group152913989: THREE.Mesh;
		group573928125: THREE.Mesh;
		group1950987988: THREE.Mesh;
		group1270993443: THREE.Mesh;
		group1815398628: THREE.Mesh;
		group1418556260: THREE.Mesh;
		group360303666: THREE.Mesh;
		group1769191577: THREE.Mesh;
		mesh1900609528: THREE.Mesh;
		mesh1900609528_1: THREE.Mesh;
		mesh1900609528_2: THREE.Mesh;
		mesh727635381: THREE.Mesh;
		mesh727635381_1: THREE.Mesh;
		mesh727635381_2: THREE.Mesh;
		mesh434366226: THREE.Mesh;
		mesh434366226_1: THREE.Mesh;
		mesh434366226_2: THREE.Mesh;
		mesh2140295573: THREE.Mesh;
		mesh2140295573_1: THREE.Mesh;
		mesh2140295573_2: THREE.Mesh;
		group1950652135: THREE.Mesh;
		mesh1174425843: THREE.Mesh;
		mesh1174425843_1: THREE.Mesh;
		mesh1174425843_2: THREE.Mesh;
		mesh2130182842: THREE.Mesh;
		mesh2130182842_1: THREE.Mesh;
		mesh2130182842_2: THREE.Mesh;
		group1970010253: THREE.Mesh;
		group1247476751: THREE.Mesh;
		mesh972715649: THREE.Mesh;
		mesh972715649_1: THREE.Mesh;
		mesh972715649_2: THREE.Mesh;
		mesh972715649_3: THREE.Mesh;
		group1756206511: THREE.Mesh;
		mesh2025258381: THREE.Mesh;
		mesh2025258381_1: THREE.Mesh;
		group605001337: THREE.Mesh;
		mesh1952414952: THREE.Mesh;
		mesh1952414952_1: THREE.Mesh;
		mesh892487588: THREE.Mesh;
		mesh892487588_1: THREE.Mesh;
		group241206949: THREE.Mesh;
		group1444810096: THREE.Mesh;
		group167726569: THREE.Mesh;
		group597386534: THREE.Mesh;
		group1165315575: THREE.Mesh;
		mesh1769749722: THREE.Mesh;
		mesh1769749722_1: THREE.Mesh;
		mesh1769749722_2: THREE.Mesh;
		mesh1769749722_3: THREE.Mesh;
		mesh1769749722_4: THREE.Mesh;
		mesh1769749722_5: THREE.Mesh;
		mesh1769749722_6: THREE.Mesh;
		mesh1769749722_7: THREE.Mesh;
		mesh1769749722_8: THREE.Mesh;
		mesh1769749722_9: THREE.Mesh;
		mesh568414040: THREE.Mesh;
		mesh568414040_1: THREE.Mesh;
		mesh1987911788: THREE.Mesh;
		mesh1987911788_1: THREE.Mesh;
		mesh99597693: THREE.Mesh;
		mesh99597693_1: THREE.Mesh;
		mesh1617223438: THREE.Mesh;
		mesh1617223438_1: THREE.Mesh;
		mesh800851294: THREE.Mesh;
		mesh800851294_1: THREE.Mesh;
		mesh282285962: THREE.Mesh;
		mesh282285962_1: THREE.Mesh;
		mesh643817545: THREE.Mesh;
		mesh643817545_1: THREE.Mesh;
		mesh1555311382: THREE.Mesh;
		mesh1555311382_1: THREE.Mesh;
		mesh1019102024: THREE.Mesh;
		mesh1019102024_1: THREE.Mesh;
		mesh1511101908: THREE.Mesh;
		mesh1511101908_1: THREE.Mesh;
		mesh248670043: THREE.Mesh;
		mesh248670043_1: THREE.Mesh;
		group717177999: THREE.Mesh;
		group414712452: THREE.Mesh;
		mesh1386167440: THREE.Mesh;
		mesh1386167440_1: THREE.Mesh;
		mesh1386167440_2: THREE.Mesh;
		mesh1386167440_3: THREE.Mesh;
		mesh1386167440_4: THREE.Mesh;
		mesh1386167440_5: THREE.Mesh;
		group665622498: THREE.Mesh;
		group468797730: THREE.Mesh;
		mesh2070643117: THREE.Mesh;
		mesh2070643117_1: THREE.Mesh;
		mesh2070643117_2: THREE.Mesh;
		mesh2070643117_3: THREE.Mesh;
		mesh2070643117_4: THREE.Mesh;
		mesh2070643117_5: THREE.Mesh;
		mesh1870537240: THREE.Mesh;
		mesh1870537240_1: THREE.Mesh;
		mesh1870537240_2: THREE.Mesh;
		mesh1536715921: THREE.Mesh;
		mesh1536715921_1: THREE.Mesh;
		mesh1536715921_2: THREE.Mesh;
		mesh664624566: THREE.Mesh;
		mesh664624566_1: THREE.Mesh;
		mesh664624566_2: THREE.Mesh;
		mesh720648363: THREE.Mesh;
		mesh720648363_1: THREE.Mesh;
		mesh720648363_2: THREE.Mesh;
		mesh1731338008: THREE.Mesh;
		mesh1731338008_1: THREE.Mesh;
		mesh1736916870: THREE.Mesh;
		mesh1736916870_1: THREE.Mesh;
		group29898793: THREE.Mesh;
		mesh1623525114: THREE.Mesh;
		mesh1623525114_1: THREE.Mesh;
	};
	materials: {
		mat17: THREE.MeshStandardMaterial;
		mat13: THREE.MeshStandardMaterial;
		mat20: THREE.MeshStandardMaterial;
		mat23: THREE.MeshStandardMaterial;
		mat10: THREE.MeshStandardMaterial;
		mat15: THREE.MeshStandardMaterial;
		mat21: THREE.MeshStandardMaterial;
		mat24: THREE.MeshStandardMaterial;
		mat19: THREE.MeshStandardMaterial;
		mat18: THREE.MeshStandardMaterial;
		mat9: THREE.MeshStandardMaterial;
		mat8: THREE.MeshStandardMaterial;
		mat12: THREE.MeshStandardMaterial;
		mat14: THREE.MeshStandardMaterial;
		mat4: THREE.MeshStandardMaterial;
		mat3: THREE.MeshStandardMaterial;
		mat16: THREE.MeshStandardMaterial;
		mat5: THREE.MeshStandardMaterial;
	};
};

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

type Props = JSX.IntrinsicElements["group"] & {
	html?: boolean;
};

export function CampingModel({ html = false, ...props }: Props) {
	const { nodes, materials } = useGLTF(
		"/assets/Mesmerized3d/camping.glb"
	) as GLTFResult;
	return (
		<group
			{...props}
			dispose={null}
		>
			<group name="Scene">
				<mesh
					name="group330264743"
					geometry={nodes.group330264743.geometry}
					material={materials.mat17}
				/>
				<mesh
					name="group756785519"
					geometry={nodes.group756785519.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1592954421"
					geometry={nodes.group1592954421.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1997237509"
					geometry={nodes.group1997237509.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1774949739"
					geometry={nodes.group1774949739.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group912174311"
					geometry={nodes.group912174311.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group2003861280"
					geometry={nodes.group2003861280.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group312988249"
					geometry={nodes.group312988249.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group1139254300"
					geometry={nodes.group1139254300.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group611470674"
					geometry={nodes.group611470674.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group1725671573"
					geometry={nodes.group1725671573.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group1910173211"
					geometry={nodes.group1910173211.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group467729922"
					geometry={nodes.group467729922.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group648914745"
					geometry={nodes.group648914745.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group1726783281"
					geometry={nodes.group1726783281.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group213706146"
					geometry={nodes.group213706146.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group2084766983"
					geometry={nodes.group2084766983.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group637283230"
					geometry={nodes.group637283230.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group625022612"
					geometry={nodes.group625022612.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group799625953"
					geometry={nodes.group799625953.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group1241182310"
					geometry={nodes.group1241182310.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group1762625985"
					geometry={nodes.group1762625985.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group2016668438"
					geometry={nodes.group2016668438.geometry}
					material={materials.mat10}
				/>
				<mesh
					name="group1211270279"
					geometry={nodes.group1211270279.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group962132412"
					geometry={nodes.group962132412.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group2045238674"
					geometry={nodes.group2045238674.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group2034554043"
					geometry={nodes.group2034554043.geometry}
					material={materials.mat20}
				/>
				<mesh
					name="group1249314938"
					geometry={nodes.group1249314938.geometry}
					material={materials.mat23}
				/>
				<group position={[0.122, 0.154, -0.288]}>
					<OverlayItem
						rotation-y={degToRad(20)}
						position={[1.2, 1.2, -0.1]}
						title={"Tent"}
						description="2 person tent, rest assured you'll be dry."
						price={129.99}
						bgColor="bg-yellow-500"
						className="transition delay-1000"
						visible={html}
					/>
					<mesh
						name="tent"
						geometry={nodes.tent.geometry}
						material={materials.mat13}
					/>
				</group>

				<mesh
					name="group612170013"
					geometry={nodes.group612170013.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group1726941988"
					geometry={nodes.group1726941988.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group535548886"
					geometry={nodes.group535548886.geometry}
					material={materials.mat23}
				/>
				<mesh
					name="group1834474229"
					geometry={nodes.group1834474229.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1828253948"
					geometry={nodes.group1828253948.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1083046558"
					geometry={nodes.group1083046558.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1173642836"
					geometry={nodes.group1173642836.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1354684915"
					geometry={nodes.group1354684915.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group179715504"
					geometry={nodes.group179715504.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group870377423"
					geometry={nodes.group870377423.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group2051321267"
					geometry={nodes.group2051321267.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group537140664"
					geometry={nodes.group537140664.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1931903066"
					geometry={nodes.group1931903066.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group81696465"
					geometry={nodes.group81696465.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1952052079"
					geometry={nodes.group1952052079.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group868215323"
					geometry={nodes.group868215323.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group965679006"
					geometry={nodes.group965679006.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group2126162799"
					geometry={nodes.group2126162799.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1146075737"
					geometry={nodes.group1146075737.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1374130805"
					geometry={nodes.group1374130805.geometry}
					material={materials.mat21}
				/>
				<mesh
					name="group903640800"
					geometry={nodes.group903640800.geometry}
					material={materials.mat21}
				/>
				<mesh
					name="group1075032789"
					geometry={nodes.group1075032789.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group774324054"
					geometry={nodes.group774324054.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1484014363"
					geometry={nodes.group1484014363.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group511150639"
					geometry={nodes.group511150639.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group2137964724"
					geometry={nodes.group2137964724.geometry}
					material={materials.mat21}
				/>
				<mesh
					name="group1541698971"
					geometry={nodes.group1541698971.geometry}
					material={materials.mat24}
				/>
				<mesh
					name="group1188624501"
					geometry={nodes.group1188624501.geometry}
					material={materials.mat24}
				/>
				<group name="group663504923">
					<mesh
						name="mesh663504923"
						geometry={nodes.mesh663504923.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh663504923_1"
						geometry={nodes.mesh663504923_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh663504923_2"
						geometry={nodes.mesh663504923_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group1088612588">
					<mesh
						name="mesh1088612588"
						geometry={nodes.mesh1088612588.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh1088612588_1"
						geometry={nodes.mesh1088612588_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1088612588_2"
						geometry={nodes.mesh1088612588_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name="group1193226793"
					geometry={nodes.group1193226793.geometry}
					material={materials.mat9}
				/>
				<mesh
					name="group460129575"
					geometry={nodes.group460129575.geometry}
					material={materials.mat9}
				/>
				<group name="group1434122196">
					<mesh
						name="mesh1434122196"
						geometry={nodes.mesh1434122196.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh1434122196_1"
						geometry={nodes.mesh1434122196_1.geometry}
						material={materials.mat10}
					/>
				</group>
				<group name="group1511301575">
					<mesh
						name="mesh1511301575"
						geometry={nodes.mesh1511301575.geometry}
						material={materials.mat10}
					/>
					<mesh
						name="mesh1511301575_1"
						geometry={nodes.mesh1511301575_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group632722702">
					<mesh
						name="mesh632722702"
						geometry={nodes.mesh632722702.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh632722702_1"
						geometry={nodes.mesh632722702_1.geometry}
						material={materials.mat10}
					/>
				</group>
				<group name="group1952899948">
					<mesh
						name="mesh1952899948"
						geometry={nodes.mesh1952899948.geometry}
						material={materials.mat10}
					/>
					<mesh
						name="mesh1952899948_1"
						geometry={nodes.mesh1952899948_1.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh1952899948_2"
						geometry={nodes.mesh1952899948_2.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group954393760">
					<mesh
						name="mesh954393760"
						geometry={nodes.mesh954393760.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh954393760_1"
						geometry={nodes.mesh954393760_1.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh954393760_2"
						geometry={nodes.mesh954393760_2.geometry}
						material={materials.mat10}
					/>
				</group>
				<group name="group811728704">
					<mesh
						name="mesh811728704"
						geometry={nodes.mesh811728704.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh811728704_1"
						geometry={nodes.mesh811728704_1.geometry}
						material={materials.mat10}
					/>
				</group>
				<group name="group470834711">
					<mesh
						name="mesh470834711"
						geometry={nodes.mesh470834711.geometry}
						material={materials.mat10}
					/>
					<mesh
						name="mesh470834711_1"
						geometry={nodes.mesh470834711_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group981371949">
					<mesh
						name="mesh981371949"
						geometry={nodes.mesh981371949.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh981371949_1"
						geometry={nodes.mesh981371949_1.geometry}
						material={materials.mat15}
					/>
				</group>
				<group name="group897427996">
					<mesh
						name="mesh897427996"
						geometry={nodes.mesh897427996.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh897427996_1"
						geometry={nodes.mesh897427996_1.geometry}
						material={materials.mat10}
					/>
				</group>
				<group name="group624108358">
					<mesh
						name="mesh624108358"
						geometry={nodes.mesh624108358.geometry}
						material={materials.mat10}
					/>
					<mesh
						name="mesh624108358_1"
						geometry={nodes.mesh624108358_1.geometry}
						material={materials.mat15}
					/>
				</group>
				<group name="group595478641">
					<mesh
						name="mesh595478641"
						geometry={nodes.mesh595478641.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh595478641_1"
						geometry={nodes.mesh595478641_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name="group2033909409"
					geometry={nodes.group2033909409.geometry}
					material={materials.mat15}
				/>
				<group name="group947843091">
					<mesh
						name="mesh947843091"
						geometry={nodes.mesh947843091.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh947843091_1"
						geometry={nodes.mesh947843091_1.geometry}
						material={materials.mat10}
					/>
				</group>
				<group name="group1774266040">
					<mesh
						name="mesh1774266040"
						geometry={nodes.mesh1774266040.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh1774266040_1"
						geometry={nodes.mesh1774266040_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group1806860140">
					<mesh
						name="mesh1806860140"
						geometry={nodes.mesh1806860140.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh1806860140_1"
						geometry={nodes.mesh1806860140_1.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh1806860140_2"
						geometry={nodes.mesh1806860140_2.geometry}
						material={materials.mat10}
					/>
				</group>
				<mesh
					name="group1936711080"
					geometry={nodes.group1936711080.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group76132093"
					geometry={nodes.group76132093.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group1215832014"
					geometry={nodes.group1215832014.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group179033160"
					geometry={nodes.group179033160.geometry}
					material={materials.mat15}
				/>
				<group
					name="backpack"
					position={[-0.514, -0.174, 0.45]}
				>
					<OverlayItem
						rotation-y={degToRad(20)}
						position={[-0.3, 0.44, 0.2]}
						title={"Backpack"}
						description="Ideal for camping and storing your belongings"
						price={49.99}
						bgColor="bg-green-500"
						className="transition delay-300"
						visible={html}
					/>
					<mesh
						name="mesh812894768"
						geometry={nodes.mesh812894768.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh812894768_1"
						geometry={nodes.mesh812894768_1.geometry}
						material={materials.mat23}
					/>
					<mesh
						name="mesh812894768_2"
						geometry={nodes.mesh812894768_2.geometry}
						material={materials.mat10}
					/>
					<mesh
						name="mesh812894768_3"
						geometry={nodes.mesh812894768_3.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh812894768_4"
						geometry={nodes.mesh812894768_4.geometry}
						material={materials.mat17}
					/>
				</group>
				<group name="group1806556219">
					<mesh
						name="mesh1806556219"
						geometry={nodes.mesh1806556219.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1806556219_1"
						geometry={nodes.mesh1806556219_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh1806556219_2"
						geometry={nodes.mesh1806556219_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group550750859">
					<mesh
						name="mesh550750859"
						geometry={nodes.mesh550750859.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh550750859_1"
						geometry={nodes.mesh550750859_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh550750859_2"
						geometry={nodes.mesh550750859_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group137140296">
					<mesh
						name="mesh137140296"
						geometry={nodes.mesh137140296.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh137140296_1"
						geometry={nodes.mesh137140296_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh137140296_2"
						geometry={nodes.mesh137140296_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group1119639877">
					<mesh
						name="mesh1119639877"
						geometry={nodes.mesh1119639877.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh1119639877_1"
						geometry={nodes.mesh1119639877_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1119639877_2"
						geometry={nodes.mesh1119639877_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group1121833705">
					<mesh
						name="mesh1121833705"
						geometry={nodes.mesh1121833705.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh1121833705_1"
						geometry={nodes.mesh1121833705_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1121833705_2"
						geometry={nodes.mesh1121833705_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name="group862771831"
					geometry={nodes.group862771831.geometry}
					material={materials.mat13}
				/>
				<group name="group906174970">
					<mesh
						name="mesh906174970"
						geometry={nodes.mesh906174970.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh906174970_1"
						geometry={nodes.mesh906174970_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh906174970_2"
						geometry={nodes.mesh906174970_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<mesh
					name="group1352282937"
					geometry={nodes.group1352282937.geometry}
					material={materials.mat8}
				/>
				<group name="group1530965799">
					<mesh
						name="mesh1530965799"
						geometry={nodes.mesh1530965799.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1530965799_1"
						geometry={nodes.mesh1530965799_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh1530965799_2"
						geometry={nodes.mesh1530965799_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group1838836646">
					<mesh
						name="mesh1838836646"
						geometry={nodes.mesh1838836646.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1838836646_1"
						geometry={nodes.mesh1838836646_1.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group1204561430">
					<mesh
						name="mesh1204561430"
						geometry={nodes.mesh1204561430.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh1204561430_1"
						geometry={nodes.mesh1204561430_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1204561430_2"
						geometry={nodes.mesh1204561430_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group416585231">
					<mesh
						name="mesh416585231"
						geometry={nodes.mesh416585231.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh416585231_1"
						geometry={nodes.mesh416585231_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh416585231_2"
						geometry={nodes.mesh416585231_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group889152651">
					<mesh
						name="mesh889152651"
						geometry={nodes.mesh889152651.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh889152651_1"
						geometry={nodes.mesh889152651_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh889152651_2"
						geometry={nodes.mesh889152651_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group1364602715">
					<mesh
						name="mesh1364602715"
						geometry={nodes.mesh1364602715.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh1364602715_1"
						geometry={nodes.mesh1364602715_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1364602715_2"
						geometry={nodes.mesh1364602715_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<mesh
					name="group587165587"
					geometry={nodes.group587165587.geometry}
					material={materials.mat8}
				/>
				<mesh
					name="group1903258221"
					geometry={nodes.group1903258221.geometry}
					material={materials.mat12}
				/>
				<mesh
					name="group1992484385"
					geometry={nodes.group1992484385.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1017972466"
					geometry={nodes.group1017972466.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1894462670"
					geometry={nodes.group1894462670.geometry}
					material={materials.mat14}
				/>
				<mesh
					name="group458100224"
					geometry={nodes.group458100224.geometry}
					material={materials.mat12}
				/>
				<mesh
					name="group1090731226"
					geometry={nodes.group1090731226.geometry}
					material={materials.mat8}
				/>
				<mesh
					name="group152913989"
					geometry={nodes.group152913989.geometry}
					material={materials.mat12}
				/>
				<mesh
					name="group573928125"
					geometry={nodes.group573928125.geometry}
					material={materials.mat12}
				/>
				<mesh
					name="group1950987988"
					geometry={nodes.group1950987988.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1270993443"
					geometry={nodes.group1270993443.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1815398628"
					geometry={nodes.group1815398628.geometry}
					material={materials.mat13}
				/>
				<mesh
					name="group1418556260"
					geometry={nodes.group1418556260.geometry}
					material={materials.mat8}
				/>
				<mesh
					name="group360303666"
					geometry={nodes.group360303666.geometry}
					material={materials.mat14}
				/>
				<mesh
					name="group1769191577"
					geometry={nodes.group1769191577.geometry}
					material={materials.mat14}
				/>
				<group name="group1900609528">
					<mesh
						name="mesh1900609528"
						geometry={nodes.mesh1900609528.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1900609528_1"
						geometry={nodes.mesh1900609528_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh1900609528_2"
						geometry={nodes.mesh1900609528_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group727635381">
					<mesh
						name="mesh727635381"
						geometry={nodes.mesh727635381.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh727635381_1"
						geometry={nodes.mesh727635381_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh727635381_2"
						geometry={nodes.mesh727635381_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group434366226">
					<mesh
						name="mesh434366226"
						geometry={nodes.mesh434366226.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh434366226_1"
						geometry={nodes.mesh434366226_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh434366226_2"
						geometry={nodes.mesh434366226_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group2140295573">
					<mesh
						name="mesh2140295573"
						geometry={nodes.mesh2140295573.geometry}
						material={materials.mat17}
					/>
					<mesh
						name="mesh2140295573_1"
						geometry={nodes.mesh2140295573_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh2140295573_2"
						geometry={nodes.mesh2140295573_2.geometry}
						material={materials.mat15}
					/>
				</group>
				<mesh
					name="group1950652135"
					geometry={nodes.group1950652135.geometry}
					material={materials.mat20}
				/>
				<group name="group1174425843">
					<mesh
						name="mesh1174425843"
						geometry={nodes.mesh1174425843.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1174425843_1"
						geometry={nodes.mesh1174425843_1.geometry}
						material={materials.mat17}
					/>
					<mesh
						name="mesh1174425843_2"
						geometry={nodes.mesh1174425843_2.geometry}
						material={materials.mat15}
					/>
				</group>
				<group name="group2130182842">
					<mesh
						name="mesh2130182842"
						geometry={nodes.mesh2130182842.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh2130182842_1"
						geometry={nodes.mesh2130182842_1.geometry}
						material={materials.mat17}
					/>
					<mesh
						name="mesh2130182842_2"
						geometry={nodes.mesh2130182842_2.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name="group1970010253"
					geometry={nodes.group1970010253.geometry}
					material={materials.mat21}
				/>
				<mesh
					name="group1247476751"
					geometry={nodes.group1247476751.geometry}
					material={materials.mat21}
				/>
				<group name="group972715649">
					<mesh
						name="mesh972715649"
						geometry={nodes.mesh972715649.geometry}
						material={materials.mat21}
					/>
					<mesh
						name="mesh972715649_1"
						geometry={nodes.mesh972715649_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh972715649_2"
						geometry={nodes.mesh972715649_2.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh972715649_3"
						geometry={nodes.mesh972715649_3.geometry}
						material={materials.mat8}
					/>
				</group>
				<mesh
					name="group1756206511"
					geometry={nodes.group1756206511.geometry}
					material={materials.mat23}
				/>
				<group name="group2025258381">
					<mesh
						name="mesh2025258381"
						geometry={nodes.mesh2025258381.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh2025258381_1"
						geometry={nodes.mesh2025258381_1.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name="group605001337"
					geometry={nodes.group605001337.geometry}
					material={materials.mat13}
				/>
				<group name="group1952414952">
					<mesh
						name="mesh1952414952"
						geometry={nodes.mesh1952414952.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1952414952_1"
						geometry={nodes.mesh1952414952_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group892487588">
					<mesh
						name="mesh892487588"
						geometry={nodes.mesh892487588.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh892487588_1"
						geometry={nodes.mesh892487588_1.geometry}
						material={materials.mat20}
					/>
				</group>
				<mesh
					name="group241206949"
					geometry={nodes.group241206949.geometry}
					material={materials.mat12}
				/>
				<mesh
					name="group1444810096"
					geometry={nodes.group1444810096.geometry}
					material={materials.mat14}
				/>
				<mesh
					name="group167726569"
					geometry={nodes.group167726569.geometry}
					material={materials.mat12}
				/>
				<mesh
					name="group597386534"
					geometry={nodes.group597386534.geometry}
					material={materials.mat8}
				/>
				<mesh
					name="group1165315575"
					geometry={nodes.group1165315575.geometry}
					material={materials.mat8}
				/>
				<group
					name="lantern"
					position={[-0.854, -0.033, 1.613]}
				>
					<OverlayItem
						rotation-y={degToRad(20)}
						position={[-0.4, -0.2, 0.25]}
						title={"Lantern"}
						description="Story time is always better with lantern."
						price={39.99}
						bgColor="bg-orange-500"
						visible={html}
					/>
					<mesh
						name="mesh1769749722"
						geometry={nodes.mesh1769749722.geometry}
						material={materials.mat8}
					/>
					<mesh
						name="mesh1769749722_1"
						geometry={nodes.mesh1769749722_1.geometry}
						material={materials.mat4}
					/>
					<mesh
						name="mesh1769749722_2"
						geometry={nodes.mesh1769749722_2.geometry}
						material={materials.mat3}
					/>
					<mesh
						name="mesh1769749722_3"
						geometry={nodes.mesh1769749722_3.geometry}
						material={materials.mat15}
					/>
					<mesh
						name="mesh1769749722_4"
						geometry={nodes.mesh1769749722_4.geometry}
						material={materials.mat13}
					/>
					<mesh
						name="mesh1769749722_5"
						geometry={nodes.mesh1769749722_5.geometry}
						material={materials.mat23}
					/>
					<mesh
						name="mesh1769749722_6"
						geometry={nodes.mesh1769749722_6.geometry}
						material={materials.mat24}
					/>
					<mesh
						name="mesh1769749722_7"
						geometry={nodes.mesh1769749722_7.geometry}
						material={materials.mat17}
					/>
					<mesh
						name="mesh1769749722_8"
						geometry={nodes.mesh1769749722_8.geometry}
						material={materials.mat12}
					/>
					<mesh
						name="mesh1769749722_9"
						geometry={nodes.mesh1769749722_9.geometry}
						material={materials.mat16}
					/>
				</group>
				<group name="group568414040">
					<mesh
						name="mesh568414040"
						geometry={nodes.mesh568414040.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh568414040_1"
						geometry={nodes.mesh568414040_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group1987911788">
					<mesh
						name="mesh1987911788"
						geometry={nodes.mesh1987911788.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh1987911788_1"
						geometry={nodes.mesh1987911788_1.geometry}
						material={materials.mat20}
					/>
				</group>
				<group name="group99597693">
					<mesh
						name="mesh99597693"
						geometry={nodes.mesh99597693.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh99597693_1"
						geometry={nodes.mesh99597693_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group1617223438">
					<mesh
						name="mesh1617223438"
						geometry={nodes.mesh1617223438.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1617223438_1"
						geometry={nodes.mesh1617223438_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group800851294">
					<mesh
						name="mesh800851294"
						geometry={nodes.mesh800851294.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh800851294_1"
						geometry={nodes.mesh800851294_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group282285962">
					<mesh
						name="mesh282285962"
						geometry={nodes.mesh282285962.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh282285962_1"
						geometry={nodes.mesh282285962_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group643817545">
					<mesh
						name="mesh643817545"
						geometry={nodes.mesh643817545.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh643817545_1"
						geometry={nodes.mesh643817545_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group1555311382">
					<mesh
						name="mesh1555311382"
						geometry={nodes.mesh1555311382.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1555311382_1"
						geometry={nodes.mesh1555311382_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group1019102024">
					<mesh
						name="mesh1019102024"
						geometry={nodes.mesh1019102024.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1019102024_1"
						geometry={nodes.mesh1019102024_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group1511101908">
					<mesh
						name="mesh1511101908"
						geometry={nodes.mesh1511101908.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1511101908_1"
						geometry={nodes.mesh1511101908_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<group name="group248670043">
					<mesh
						name="mesh248670043"
						geometry={nodes.mesh248670043.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh248670043_1"
						geometry={nodes.mesh248670043_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name="group717177999"
					geometry={nodes.group717177999.geometry}
					material={materials.mat15}
				/>
				<mesh
					name="group414712452"
					geometry={nodes.group414712452.geometry}
					material={materials.mat15}
				/>
				<group
					name="sleeping-bag"
					position={[-0.071, -0.366, 1.09]}
				>
					<OverlayItem
						position-x={0.1}
						position-y={0.25}
						position-z={-0.14}
						rotation-x={-degToRad(30)}
						title={"Sleeping Bag"}
						description={"Keeps you warm and comfortable."}
						price={"79.99"}
						bgColor={"bg-blue-500"}
						className="transition delay-700"
						visible={html}
					/>
					<mesh
						name="mesh1386167440"
						geometry={nodes.mesh1386167440.geometry}
						material={materials.mat16}
					/>
					<mesh
						name="mesh1386167440_1"
						geometry={nodes.mesh1386167440_1.geometry}
						material={materials.mat4}
					/>
					<mesh
						name="mesh1386167440_2"
						geometry={nodes.mesh1386167440_2.geometry}
						material={materials.mat3}
					/>
					<mesh
						name="mesh1386167440_3"
						geometry={nodes.mesh1386167440_3.geometry}
						material={materials.mat5}
					/>
					<mesh
						name="mesh1386167440_4"
						geometry={nodes.mesh1386167440_4.geometry}
						material={materials.mat17}
					/>
					<mesh
						name="mesh1386167440_5"
						geometry={nodes.mesh1386167440_5.geometry}
						material={materials.mat23}
					/>
				</group>
				<mesh
					name="group665622498"
					geometry={nodes.group665622498.geometry}
					material={materials.mat9}
				/>
				<mesh
					name="group468797730"
					geometry={nodes.group468797730.geometry}
					material={materials.mat9}
				/>
				<group name="group2070643117">
					<mesh
						name="mesh2070643117"
						geometry={nodes.mesh2070643117.geometry}
						material={materials.mat16}
					/>
					<mesh
						name="mesh2070643117_1"
						geometry={nodes.mesh2070643117_1.geometry}
						material={materials.mat4}
					/>
					<mesh
						name="mesh2070643117_2"
						geometry={nodes.mesh2070643117_2.geometry}
						material={materials.mat3}
					/>
					<mesh
						name="mesh2070643117_3"
						geometry={nodes.mesh2070643117_3.geometry}
						material={materials.mat5}
					/>
					<mesh
						name="mesh2070643117_4"
						geometry={nodes.mesh2070643117_4.geometry}
						material={materials.mat23}
					/>
					<mesh
						name="mesh2070643117_5"
						geometry={nodes.mesh2070643117_5.geometry}
						material={materials.mat17}
					/>
				</group>
				<group name="group1870537240">
					<mesh
						name="mesh1870537240"
						geometry={nodes.mesh1870537240.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1870537240_1"
						geometry={nodes.mesh1870537240_1.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh1870537240_2"
						geometry={nodes.mesh1870537240_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group1536715921">
					<mesh
						name="mesh1536715921"
						geometry={nodes.mesh1536715921.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh1536715921_1"
						geometry={nodes.mesh1536715921_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1536715921_2"
						geometry={nodes.mesh1536715921_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group664624566">
					<mesh
						name="mesh664624566"
						geometry={nodes.mesh664624566.geometry}
						material={materials.mat19}
					/>
					<mesh
						name="mesh664624566_1"
						geometry={nodes.mesh664624566_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh664624566_2"
						geometry={nodes.mesh664624566_2.geometry}
						material={materials.mat18}
					/>
				</group>
				<group name="group720648363">
					<mesh
						name="mesh720648363"
						geometry={nodes.mesh720648363.geometry}
						material={materials.mat18}
					/>
					<mesh
						name="mesh720648363_1"
						geometry={nodes.mesh720648363_1.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh720648363_2"
						geometry={nodes.mesh720648363_2.geometry}
						material={materials.mat19}
					/>
				</group>
				<group name="group1731338008">
					<mesh
						name="mesh1731338008"
						geometry={nodes.mesh1731338008.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh1731338008_1"
						geometry={nodes.mesh1731338008_1.geometry}
						material={materials.mat20}
					/>
				</group>
				<group name="group1736916870">
					<mesh
						name="mesh1736916870"
						geometry={nodes.mesh1736916870.geometry}
						material={materials.mat20}
					/>
					<mesh
						name="mesh1736916870_1"
						geometry={nodes.mesh1736916870_1.geometry}
						material={materials.mat9}
					/>
				</group>
				<mesh
					name="group29898793"
					geometry={nodes.group29898793.geometry}
					material={materials.mat15}
				/>
				<group name="group1623525114">
					<mesh
						name="mesh1623525114"
						geometry={nodes.mesh1623525114.geometry}
						material={materials.mat9}
					/>
					<mesh
						name="mesh1623525114_1"
						geometry={nodes.mesh1623525114_1.geometry}
						material={materials.mat20}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/assets/Mesmerized3d/camping.glb");
