/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/assets/SciFiCoridor/scificoridor-threejs.glb -o features/SciFiCoridor/components/Model.tsx -t 
*/

import * as THREE from "three";
import React, { useEffect, useLayoutEffect, useMemo, useRef } from "react";
import {
	useGLTF,
	useAnimations,
	MeshReflectorMaterial,
} from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { applyProps } from "@react-three/fiber";

type GLTFResult = GLTF & {
	nodes: {
		Crate004_1: THREE.Mesh;
		Crate004_2: THREE.Mesh;
		CrateLock003: THREE.Mesh;
		Crate003_1: THREE.Mesh;
		Crate003_2: THREE.Mesh;
		CrateLock005: THREE.Mesh;
		Walls: THREE.Mesh;
		Plane006: THREE.Mesh;
		Plane006_1: THREE.Mesh;
		WallPanels_1: THREE.Mesh;
		WallPanels_2: THREE.Mesh;
		Door: THREE.Mesh;
		DoorPanelLeft: THREE.Mesh;
		DoorDisplay: THREE.Mesh;
		DoorDisplayFrame: THREE.Mesh;
		DoorPanelRight: THREE.Mesh;
		Entrance: THREE.Mesh;
		BoltEntrance: THREE.Mesh;
		BoltEntrance001: THREE.Mesh;
		BoltEntrance002: THREE.Mesh;
		BoltEntrance003: THREE.Mesh;
		BoltEntrance004: THREE.Mesh;
		BoltEntrance005: THREE.Mesh;
		EntranceNeon: THREE.Mesh;
		EntrancePanels: THREE.Mesh;
		EntranceTube: THREE.Mesh;
		Platform: THREE.Mesh;
		PlatformPanel1: THREE.Mesh;
		PlatformPanel2: THREE.Mesh;
		PlatformRails: THREE.Mesh;
		PlatformRailsPanel: THREE.Mesh;
		PlatformTop: THREE.Mesh;
		Floor: THREE.Mesh;
		FloorPanel: THREE.Mesh;
		Generator: THREE.Mesh;
		GeneratorBackPanel: THREE.Mesh;
		GeneratorBody: THREE.Mesh;
		GeneratorFrontPanel: THREE.Mesh;
		GeneratorTopPanel: THREE.Mesh;
		Pipe: THREE.Mesh;
		Pipe2: THREE.Mesh;
		Crate: THREE.Mesh;
		Crate_1: THREE.Mesh;
		CrateLock: THREE.Mesh;
		CrateLock001: THREE.Mesh;
		CrateLock002: THREE.Mesh;
		BoltPillar: THREE.Mesh;
		BoltPillar001: THREE.Mesh;
		BoltPillar002: THREE.Mesh;
		BoltDoor: THREE.Mesh;
		BoltDoor001: THREE.Mesh;
		BoltDoor002: THREE.Mesh;
		BoltDoor003: THREE.Mesh;
		BoltPlatform: THREE.Mesh;
		BoltPlatform001: THREE.Mesh;
		BoltPlatform002: THREE.Mesh;
		BoltGeneratorRing: THREE.Mesh;
		BoltGeneratorRing001: THREE.Mesh;
		BoltGenerator: THREE.Mesh;
		BoltGenerator001: THREE.Mesh;
		BoltFloor: THREE.Mesh;
		BoltFloor001: THREE.Mesh;
		BoltFloor002: THREE.Mesh;
		BoltFloor003: THREE.Mesh;
	};
	materials: {
		["Metal.004"]: THREE.MeshStandardMaterial;
		["Accent.003"]: THREE.MeshStandardMaterial;
		["Light.003"]: THREE.MeshStandardMaterial;
		Material: THREE.MeshStandardMaterial;
		White: THREE.MeshStandardMaterial;
		Light: THREE.MeshStandardMaterial;
		Accent: THREE.MeshStandardMaterial;
		Metal: THREE.MeshStandardMaterial;
		LightDoor: THREE.MeshStandardMaterial;
		["Metal.001"]: THREE.MeshStandardMaterial;
	};
};

type ActionName = "Animation";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>(null);
	const { nodes, materials, animations } = useGLTF(
		"/assets/SciFiCoridor/scificoridor-threejs.glb"
	) as GLTFResult;
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions["Animation"]?.play();
	}, [actions]);

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
		>
			<group name="Scene">
				<group
					name="NurbsPath"
					position={[-5.611, 1.761, -0.671]}
				>
					<group
						name="Crate004"
						position={[-1.924, -0.013, -0.001]}
						rotation={[-0.032, 0.309, -0.02]}
					>
						<mesh
							name="Crate004_1"
							geometry={nodes.Crate004_1.geometry}
							material={materials["Metal.004"]}
							castShadow
						/>
						<mesh
							name="Crate004_2"
							geometry={nodes.Crate004_2.geometry}
							material={materials["Accent.003"]}
						/>
						<mesh
							name="CrateLock003"
							geometry={nodes.CrateLock003.geometry}
							material={materials["Light.003"]}
							scale={0.771}
						/>
					</group>
				</group>
				<group
					name="NurbsPath001"
					position={[-5.611, 1.761, -0.671]}
				>
					<group
						name="Crate006"
						position={[-1.937, -0.017, -0.001]}
						rotation={[-0.017, 0.31, -0.069]}
					>
						<mesh
							name="Crate003_1"
							geometry={nodes.Crate003_1.geometry}
							material={materials["Metal.004"]}
							castShadow
						/>
						<mesh
							name="Crate003_2"
							geometry={nodes.Crate003_2.geometry}
							material={materials["Accent.003"]}
						/>
						<mesh
							name="CrateLock005"
							geometry={nodes.CrateLock005.geometry}
							material={materials["Light.003"]}
							scale={0.771}
						/>
					</group>
				</group>
				<mesh
					name="Walls"
					geometry={nodes.Walls.geometry}
					material={materials.Material}
				/>
				<group name="WallStructure">
					<mesh
						name="Plane006"
						geometry={nodes.Plane006.geometry}
						material={materials.White}
					/>
					<mesh
						name="Plane006_1"
						geometry={nodes.Plane006_1.geometry}
						material={materials.Light}
					/>
				</group>
				<group name="WallPanels">
					<mesh
						name="WallPanels_1"
						geometry={nodes.WallPanels_1.geometry}
						material={materials.White}
					/>
					<mesh
						name="WallPanels_2"
						geometry={nodes.WallPanels_2.geometry}
						material={materials.Accent}
					/>
				</group>
				<mesh
					name="Door"
					geometry={nodes.Door.geometry}
					material={materials.Accent}
					position={[1.013, 2.131, -4]}
				>
					<mesh
						name="DoorPanelLeft"
						geometry={nodes.DoorPanelLeft.geometry}
						material={materials.Metal}
						position={[0, 0, -0.092]}
					/>
					<mesh
						name="DoorDisplay"
						geometry={nodes.DoorDisplay.geometry}
						material={materials.LightDoor}
					/>
					<mesh
						name="DoorDisplayFrame"
						geometry={nodes.DoorDisplayFrame.geometry}
						material={materials.Metal}
					/>
					<mesh
						name="DoorPanelRight"
						geometry={nodes.DoorPanelRight.geometry}
						material={materials.Metal}
						position={[0, 0, -0.092]}
					/>
				</mesh>
				<mesh
					name="Entrance"
					geometry={nodes.Entrance.geometry}
					material={materials.Metal}
					position={[-3.913, 2.702, -0.732]}
					scale={1.286}
				>
					<mesh
						name="BoltEntrance"
						geometry={nodes.BoltEntrance.geometry}
						material={materials["Metal.001"]}
						position={[-0.099, 1.12, 0.133]}
						rotation={[Math.PI / 2, 0, -Math.PI / 2]}
						scale={0.778}
					/>
					<mesh
						name="BoltEntrance001"
						geometry={nodes.BoltEntrance001.geometry}
						material={materials["Metal.001"]}
						position={[-0.099, 1.12, -0.131]}
						rotation={[Math.PI / 2, 0, -Math.PI / 2]}
						scale={0.778}
					/>
					<mesh
						name="BoltEntrance002"
						geometry={nodes.BoltEntrance002.geometry}
						material={materials["Metal.001"]}
						position={[-0.099, -0.178, -1.124]}
						rotation={[-Math.PI, 0, -Math.PI / 2]}
						scale={0.778}
					/>
					<mesh
						name="BoltEntrance003"
						geometry={nodes.BoltEntrance003.geometry}
						material={materials["Metal.001"]}
						position={[-0.099, 0.051, -1.126]}
						rotation={[-Math.PI, 0, -Math.PI / 2]}
						scale={0.778}
					/>
					<mesh
						name="BoltEntrance004"
						geometry={nodes.BoltEntrance004.geometry}
						material={materials["Metal.001"]}
						position={[-0.099, -0.178, 1.124]}
						rotation={[-Math.PI, 0, -Math.PI / 2]}
						scale={0.778}
					/>
					<mesh
						name="BoltEntrance005"
						geometry={nodes.BoltEntrance005.geometry}
						material={materials["Metal.001"]}
						position={[-0.099, 0.051, 1.122]}
						rotation={[-Math.PI, 0, -Math.PI / 2]}
						scale={0.778}
					/>
					<mesh
						name="EntranceNeon"
						geometry={nodes.EntranceNeon.geometry}
						material={materials.Light}
					/>
					<mesh
						name="EntrancePanels"
						geometry={nodes.EntrancePanels.geometry}
						material={materials.White}
						receiveShadow
					/>
					<mesh
						name="EntranceTube"
						geometry={nodes.EntranceTube.geometry}
						material={materials.Metal}
					/>
				</mesh>
				<mesh
					name="Platform"
					geometry={nodes.Platform.geometry}
					material={materials.Metal}
					castShadow
				>
					<mesh
						name="PlatformPanel1"
						geometry={nodes.PlatformPanel1.geometry}
						material={materials.Metal}
					/>
					<mesh
						name="PlatformPanel2"
						geometry={nodes.PlatformPanel2.geometry}
						material={materials.Accent}
					/>
					<mesh
						name="PlatformRails"
						geometry={nodes.PlatformRails.geometry}
						material={nodes.PlatformRails.material}
					/>
					<mesh
						name="PlatformRailsPanel"
						geometry={nodes.PlatformRailsPanel.geometry}
						material={materials.White}
						position={[-1.296, 1.686, 1.307]}
					/>
					<mesh
						name="PlatformTop"
						geometry={nodes.PlatformTop.geometry}
						material={materials.Metal}
						receiveShadow
					/>
				</mesh>
				<mesh
					name="Floor"
					geometry={nodes.Floor.geometry}
					material={materials.Metal}
					receiveShadow
				>
					{/* <MeshReflectorMaterial
						blur={[300, 50]}
						resolution={1024}
						mixBlur={1}
						mixStrength={100}
						roughness={1}
						depthScale={1.2}
						minDepthThreshold={0.4}
						maxDepthThreshold={1.4}
						color="#202020"
						metalness={0.8}
						mirror={0}
					/> */}
					<mesh
						name="FloorPanel"
						geometry={nodes.FloorPanel.geometry}
						material={materials.Accent}
					/>
				</mesh>
				<mesh
					name="Generator"
					geometry={nodes.Generator.geometry}
					material={materials.Metal}
					position={[2.094, 0.011, 1.713]}
				>
					<mesh
						name="GeneratorBackPanel"
						geometry={nodes.GeneratorBackPanel.geometry}
						material={materials.White}
					/>
					<mesh
						name="GeneratorBody"
						geometry={nodes.GeneratorBody.geometry}
						material={materials.Accent}
					/>
					<mesh
						name="GeneratorFrontPanel"
						geometry={nodes.GeneratorFrontPanel.geometry}
						material={materials.White}
					/>
					<mesh
						name="GeneratorTopPanel"
						geometry={nodes.GeneratorTopPanel.geometry}
						material={materials.Metal}
					/>
				</mesh>
				<mesh
					name="Pipe"
					geometry={nodes.Pipe.geometry}
					material={materials.Metal}
					position={[3.711, 0.271, -1.139]}
					scale={0.781}
				>
					<mesh
						name="Pipe2"
						geometry={nodes.Pipe2.geometry}
						material={materials.Accent}
						position={[0.165, 0, -0.813]}
						scale={[2.056, 2.056, 1.281]}
					/>
				</mesh>
				<group
					name="Crate002"
					position={[-2.565, 2.59, -3.074]}
					rotation={[0, 0.219, 0]}
				>
					<mesh
						name="Crate"
						geometry={nodes.Crate.geometry}
						material={materials["Metal.004"]}
						castShadow
					/>
					<mesh
						name="Crate_1"
						geometry={nodes.Crate_1.geometry}
						material={materials["Accent.003"]}
					/>
					<mesh
						name="CrateLock"
						geometry={nodes.CrateLock.geometry}
						material={materials["Light.003"]}
						scale={0.771}
					/>
				</group>
				<group
					name="Crate001"
					position={[-2.085, 1.426, -3.074]}
					rotation={[0, 0.413, 0]}
				>
					<mesh
						name="Crate"
						geometry={nodes.Crate.geometry}
						material={materials["Metal.004"]}
					/>
					<mesh
						name="Crate_1"
						geometry={nodes.Crate_1.geometry}
						material={materials["Accent.003"]}
					/>
					<mesh
						name="CrateLock001"
						geometry={nodes.CrateLock001.geometry}
						material={materials["Light.003"]}
						scale={0.771}
					/>
				</group>
				<group
					name="Crate003"
					position={[-3.075, 1.426, -3.185]}
					rotation={[0, -0.11, 0]}
				>
					<mesh
						name="Crate"
						geometry={nodes.Crate.geometry}
						material={materials["Metal.004"]}
					/>
					<mesh
						name="Crate_1"
						geometry={nodes.Crate_1.geometry}
						material={materials["Accent.003"]}
					/>
					<mesh
						name="CrateLock002"
						geometry={nodes.CrateLock002.geometry}
						material={materials["Light.003"]}
						scale={0.771}
					/>
				</group>
				<mesh
					name="BoltPillar"
					geometry={nodes.BoltPillar.geometry}
					material={materials["Metal.001"]}
					position={[3.29, 4.852, -3.355]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="BoltPillar001"
					geometry={nodes.BoltPillar001.geometry}
					material={materials["Metal.001"]}
					position={[-1.31, 4.852, -3.355]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="BoltPillar002"
					geometry={nodes.BoltPillar002.geometry}
					material={materials["Metal.001"]}
					position={[-3.359, 4.832, 3.266]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/>
				<mesh
					name="BoltDoor"
					geometry={nodes.BoltDoor.geometry}
					material={materials["Metal.001"]}
					position={[2.38, 3.383, -3.668]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="BoltDoor001"
					geometry={nodes.BoltDoor001.geometry}
					material={materials["Metal.001"]}
					position={[-0.352, 3.649, -3.668]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="BoltDoor002"
					geometry={nodes.BoltDoor002.geometry}
					material={materials["Metal.001"]}
					position={[-0.352, 3.383, -3.668]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="BoltDoor003"
					geometry={nodes.BoltDoor003.geometry}
					material={materials["Metal.001"]}
					position={[2.38, 3.654, -3.668]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="BoltPlatform"
					geometry={nodes.BoltPlatform.geometry}
					material={materials["Metal.001"]}
					position={[-1.344, 1.456, 1.969]}
					rotation={[-2.604, 0.537, -Math.PI]}
				/>
				<mesh
					name="BoltPlatform001"
					geometry={nodes.BoltPlatform001.geometry}
					material={materials["Metal.001"]}
					position={[-1.345, 0.932, 2.848]}
					rotation={[-2.604, 0.537, -Math.PI]}
				/>
				<mesh
					name="BoltPlatform002"
					geometry={nodes.BoltPlatform002.geometry}
					material={materials["Metal.001"]}
					position={[-1.34, 0.449, 3.66]}
					rotation={[-2.604, 0.537, -Math.PI]}
				/>
				<mesh
					name="BoltGeneratorRing"
					geometry={nodes.BoltGeneratorRing.geometry}
					material={materials["Metal.001"]}
					position={[3.361, 0.532, 0.981]}
					rotation={[-Math.PI, 0.537, -Math.PI]}
				/>
				<mesh
					name="BoltGeneratorRing001"
					geometry={nodes.BoltGeneratorRing001.geometry}
					material={materials["Metal.001"]}
					position={[3.361, 0.532, 2.436]}
					rotation={[-Math.PI, 0.537, -Math.PI]}
				/>
				<mesh
					name="BoltGenerator"
					geometry={nodes.BoltGenerator.geometry}
					material={materials["Metal.001"]}
					position={[3.181, 1.315, 2.083]}
					rotation={[0.344, -0.309, -1.462]}
				/>
				<mesh
					name="BoltGenerator001"
					geometry={nodes.BoltGenerator001.geometry}
					material={materials["Metal.001"]}
					position={[3.193, 1.315, 1.343]}
					rotation={[0.344, 0.309, -1.679]}
				/>
				<mesh
					name="BoltFloor"
					geometry={nodes.BoltFloor.geometry}
					material={materials["Metal.001"]}
					position={[-0.44, 0.057, 3.726]}
					rotation={[0, -1.557, 0]}
				/>
				<mesh
					name="BoltFloor001"
					geometry={nodes.BoltFloor001.geometry}
					material={materials["Metal.001"]}
					position={[0.535, 0.057, 3.726]}
					rotation={[0, -1.557, 0]}
				/>
				<mesh
					name="BoltFloor002"
					geometry={nodes.BoltFloor002.geometry}
					material={materials["Metal.001"]}
					position={[0.51, 0.057, -2.742]}
					rotation={[0, -1.557, 0]}
				/>
				<mesh
					name="BoltFloor003"
					geometry={nodes.BoltFloor003.geometry}
					material={materials["Metal.001"]}
					position={[1.511, 0.057, -2.742]}
					rotation={[0, -1.557, 0]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/assets/SciFiCoridor/scificoridor-threejs.glb");
